lines = []
lines.append('# ROTINAS OPERACIONAIS — OLIVE GARDEN BRAND INTELLIGENCE\n')
lines.append('\n')
lines.append('## ATUALIZACOES DIARIAS\n')
lines.append('\n')
lines.append('### 1. Atualizar Vendas — Operacao Geral (Salao)\n')
lines.append('Executar quando receber o arquivo DASH VENDAS atualizado.\n')
lines.append('\n')
lines.append('`powershell\n')
lines.append('copy "C:\\olive-garden-reviews\\data\\Vendas_Geral\\NOME_DO_ARQUIVO.xlsx" "C:\\olive-garden-reviews\\data\\dash_vendas.xlsx"\n')
lines.append('python reimportar_vendas_diarias.py\n')
lines.append('python aprender_modelo.py\n')
lines.append('`\n')
lines.append('\n')
lines.append('**Importante:** substituir NOME_DO_ARQUIVO pelo nome real do arquivo recebido.\n')
lines.append('O script aprender_modelo.py deve ser rodado APOS confirmar que o reimport foi bem-sucedido.\n')
lines.append('\n')
lines.append('---\n')
lines.append('\n')
lines.append('### 2. Atualizar Vendas iFood\n')
lines.append('Executar quando receber o arquivo iFood_Vendas atualizado.\n')
lines.append('\n')
lines.append('`powershell\n')
lines.append('python importar_ifood_vendas.py\n')
lines.append('`\n')
lines.append('\n')
lines.append('**Observacao:** o script limpa automaticamente o periodo parcial anterior antes de importar o novo.\n')
lines.append('Os arquivos devem estar em: C:\\olive-garden-reviews\\data\\ifood_vendas\\\n')
lines.append('\n')
lines.append('---\n')
lines.append('\n')
lines.append('### 3. Atualizar Pesquisa GSS\n')
lines.append('Executar quando receber novos arquivos Brazil FW e Brazil OG Comments.\n')
lines.append('\n')
lines.append('`powershell\n')
lines.append('copy "CAMINHO_ORIGEM\\Brazil FW*.xlsx" "C:\\olive-garden-reviews\\data\\"\n')
lines.append('copy "CAMINHO_ORIGEM\\Brazil OG Comments*.xlsx" "C:\\olive-garden-reviews\\data\\"\n')
lines.append('python importar_pesquisa.py\n')
lines.append('`\n')
lines.append('\n')
lines.append('---\n')
lines.append('\n')
lines.append('### 4. Atualizacao Automatica (Task Scheduler — 9h)\n')
lines.append('Roda automaticamente todo dia as 9h via Windows Task Scheduler.\n')
lines.append('Atualiza: Google Reviews, noticias, sentimento, banco Supabase.\n')
lines.append('\n')
lines.append('`powershell\n')
lines.append('python atualizar_tudo.py\n')
lines.append('`\n')
lines.append('\n')
lines.append('**Observacao:** conexao ao Supabase so funciona pelo hotspot do celular.\n')
lines.append('\n')
lines.append('---\n')
lines.append('\n')
lines.append('## SISTEMA DE APRENDIZADO CONTINUO\n')
lines.append('\n')
lines.append('O script prender_modelo.py executa 3 etapas:\n')
lines.append('\n')
lines.append('1. **Calcula erros passados** — compara projecoes anteriores com o realizado\n')
lines.append('2. **Registra novas projecoes** — salva projecoes dos proximos 28 dias no banco\n')
lines.append('3. **Recalibra parametros** — atualiza MAPE e bias por filial\n')
lines.append('\n')
lines.append('Os dados ficam na tabela projecoes_historico e modelo_parametros no Supabase.\n')
lines.append('Com o tempo, o modelo se torna cada vez mais preciso por filial.\n')
lines.append('\n')
lines.append('---\n')
lines.append('\n')
lines.append('## RESTAURAR VERSAO ESTAVEL\n')
lines.append('\n')
lines.append('Em caso de erro grave no dashboard.py:\n')
lines.append('\n')
lines.append('`powershell\n')
lines.append('# Restaurar ultimo commit\n')
lines.append('git checkout HEAD -- dashboard.py\n')
lines.append('\n')
lines.append('# Restaurar versao estavel 18/05/2026\n')
lines.append('git checkout v-estavel-20260518 -- dashboard.py\n')
lines.append('`\n')
lines.append('\n')
lines.append('---\n')
lines.append('\n')
lines.append('## BANCO DE DADOS SUPABASE\n')
lines.append('\n')
lines.append('| Tabela | Conteudo | Script de atualizacao |\n')
lines.append('|---|---|---|\n')
lines.append('| vendas_diarias | 502 dias x 6 filiais | reimportar_vendas_diarias.py |\n')
lines.append('| ifood_vendas | vendas iFood por periodo | importar_ifood_vendas.py |\n')
lines.append('| pesquisa_performance | GSS topbox por filial | importar_pesquisa.py |\n')
lines.append('| pesquisa_comments | comentarios internos | importar_pesquisa.py |\n')
lines.append('| reviews | Google + TripAdvisor + iFood | atualizar_tudo.py |\n')
lines.append('| social | comentarios Instagram | atualizar_tudo.py |\n')
lines.append('| projecoes_historico | historico de projecoes | aprender_modelo.py |\n')
lines.append('| modelo_parametros | parametros calibrados | aprender_modelo.py |\n')
lines.append('\n')
lines.append('---\n')
lines.append('\n')
lines.append('## CREDENCIAIS\n')
lines.append('\n')
lines.append('- Dashboard: https://olive-garden-intelligence-y6fxcw4xtblkyca3tsha8g.streamlit.app/\n')
lines.append('- Senha: olivegarden2026\n')
lines.append('- Repositorio: https://github.com/Guilourencal/olive-garden-intelligence\n')
lines.append('- Supabase: aws-1-sa-east-1.pooler.supabase.com:6543\n')
lines.append('\n')
lines.append('---\n')
lines.append('\n')
lines.append('*Ultima atualizacao: 19/05/2026*\n')

open('README_ROTINAS.md', 'w', encoding='utf-8').write(''.join(lines))
print('OK')
