lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')

nova = []
nova.append('    if visao_sel == "Operacao Geral":')
nova.append('        import calendar')
nova.append('        from datetime import datetime, timedelta')
nova.append('        df_vd = df_vendas_diarias.copy()')
nova.append('        df_vd["data"] = pd.to_datetime(df_vd["data"])')
nova.append('        df_vd["filial_curta"] = df_vd["filial"].str.replace("Olive Garden - ", "", regex=False)')
nova.append('')
nova.append('        # Filtros')
nova.append('        col_f1, col_f2, col_f3 = st.columns(3)')
nova.append('        with col_f1:')
nova.append('            anos = sorted(df_vd["ano"].dropna().unique().astype(int), reverse=True)')
nova.append('            ano_sel = st.selectbox("Ano:", anos, key="ano_vd")')
nova.append('        with col_f2:')
nova.append('            meses_ord = ["jan","fev","mar","abr","mai","jun","jul","ago","set","out","nov","dez"]')
nova.append('            meses_disp = [m for m in meses_ord if m in df_vd[df_vd["ano"]==ano_sel]["mes"].str[:3].str.lower().unique()]')
nova.append('            mes_sel = st.selectbox("Mes:", ["Todos"] + meses_disp, key="mes_vd")')
nova.append('        with col_f3:')
nova.append('            filiais_vd = ["Todas"] + sorted(df_vd["filial_curta"].unique())')
nova.append('            filial_vd_sel = st.selectbox("Filial:", filiais_vd, key="filial_vd")')
nova.append('')
nova.append('        df_vd_f = df_vd[df_vd["ano"] == ano_sel].copy()')
nova.append('        if mes_sel != "Todos":')
nova.append('            df_vd_f = df_vd_f[df_vd_f["mes"].str[:3].str.lower() == mes_sel]')
nova.append('        if filial_vd_sel != "Todas":')
nova.append('            df_vd_f = df_vd_f[df_vd_f["filial_curta"] == filial_vd_sel]')
nova.append('')
nova.append('        # KPIs')
nova.append('        vt = df_vd_f["venda_salao"].sum()')
nova.append('        mt = df_vd_f["meta_venda"].sum()')
nova.append('        va1 = df_vd_f["venda_ano1"].sum()')
nova.append('        gc = df_vd_f["gc_salao"].sum()')
nova.append('        tk = vt / gc if gc > 0 else 0')
nova.append('        pct_meta = (vt/mt - 1)*100 if mt > 0 else 0')
nova.append('        pct_ano1 = (vt/va1 - 1)*100 if va1 > 0 else 0')
nova.append('        vt_fmt = f"R$ {vt:,.0f}".replace(",",".")')
nova.append('        mt_fmt = f"R$ {mt:,.0f}".replace(",",".")')
nova.append('        va1_fmt = f"R$ {va1:,.0f}".replace(",",".")')
nova.append('        tk_fmt = f"R$ {tk:.0f}"')
nova.append('        gc_fmt = f"{int(gc):,}".replace(",",".")')
nova.append('')
nova.append('        # Cards executivos')
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Visao Executiva — Salao</div>\', unsafe_allow_html=True)')
nova.append('            cols_c = st.columns(3)')
nova.append('            seta_meta = "▲" if pct_meta >= 0 else "▼"')
nova.append('            cor_meta2 = "#2e6b3e" if pct_meta >= 0 else "#c0392b"')
nova.append('            seta_ano1 = "▲" if pct_ano1 >= 0 else "▼"')
nova.append('            cor_ano12 = "#2e6b3e" if pct_ano1 >= 0 else "#c0392b"')
nova.append('            with cols_c[0]:')
nova.append('                st.markdown(f\'\'\'<div style="background:#3D2B1F; border-radius:10px; padding:20px; color:#F5F0E8;">')
nova.append('                    <div style="font-size:9px; color:#D8CFC0; letter-spacing:2px; margin-bottom:12px;">VENDA SALAO</div>')
nova.append('                    <div style="font-size:28px; font-weight:800; margin-bottom:8px;">{vt_fmt}</div>')
nova.append('                    <div style="display:flex; justify-content:space-between; align-items:center; padding-top:10px; border-top:1px solid rgba(255,255,255,0.1);">')
nova.append('                    <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:2px;">BUDGET</div>')
nova.append('                    <div style="font-size:12px; color:#D8CFC0;">{mt_fmt}</div></div>')
nova.append('                    <div style="font-size:18px; font-weight:700; color:{cor_meta2};">{seta_meta} {pct_meta:+.1f}%</div>')
nova.append('                    </div></div>\'\'\', unsafe_allow_html=True)')
nova.append('            with cols_c[1]:')
nova.append('                st.markdown(f\'\'\'<div style="background:#3D2B1F; border-radius:10px; padding:20px; color:#F5F0E8;">')
nova.append('                    <div style="font-size:9px; color:#D8CFC0; letter-spacing:2px; margin-bottom:12px;">VENDA SALAO</div>')
nova.append('                    <div style="font-size:28px; font-weight:800; margin-bottom:8px;">{vt_fmt}</div>')
nova.append('                    <div style="display:flex; justify-content:space-between; align-items:center; padding-top:10px; border-top:1px solid rgba(255,255,255,0.1);">')
nova.append('                    <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:2px;">ANO ANTERIOR</div>')
nova.append('                    <div style="font-size:12px; color:#D8CFC0;">{va1_fmt}</div></div>')
nova.append('                    <div style="font-size:18px; font-weight:700; color:{cor_ano12};">{seta_ano1} {pct_ano1:+.1f}%</div>')
nova.append('                    </div></div>\'\'\', unsafe_allow_html=True)')
nova.append('            with cols_c[2]:')
nova.append('                hdc_medio = df_vd_f["venda_por_hdc"].mean()')
nova.append('                hdc_fmt = f"R$ {hdc_medio:.0f}" if pd.notna(hdc_medio) else "-"')
nova.append('                st.markdown(f\'\'\'<div style="background:#3D2B1F; border-radius:10px; padding:20px; color:#F5F0E8;">')
nova.append('                    <div style="font-size:9px; color:#D8CFC0; letter-spacing:2px; margin-bottom:12px;">OPERACAO SALAO</div>')
nova.append('                    <div style="display:grid; grid-template-columns:1fr 1fr; gap:16px;">')
nova.append('                    <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:4px;">GUEST COUNT</div>')
nova.append('                    <div style="font-size:22px; font-weight:800;">{gc_fmt}</div></div>')
nova.append('                    <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:4px;">TICKET MEDIO</div>')
nova.append('                    <div style="font-size:22px; font-weight:800; color:#8B9A2E;">{tk_fmt}</div></div>')
nova.append('                    <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:4px;">VENDA/HDC</div>')
nova.append('                    <div style="font-size:18px; font-weight:700; color:#8B9A2E;">{hdc_fmt}</div></div>')
nova.append('                    </div></div>\'\'\', unsafe_allow_html=True)')
nova.append('')
nova.append('        st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('        # Evolucao acumulada')
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Evolucao Acumulada — Salao</div>\', unsafe_allow_html=True)')
nova.append('            df_evo = df_vd_f.groupby("data").agg(venda_salao=("venda_salao","sum"), meta_venda=("meta_venda","sum"), venda_ano1=("venda_ano1","sum")).reset_index().sort_values("data")')
nova.append('            fig_evo = go.Figure()')
nova.append('            fig_evo.add_trace(go.Scatter(x=df_evo["data"], y=df_evo["venda_salao"].cumsum(), mode="lines", name="Realizado", line=dict(color=VERDE, width=3)))')
nova.append('            fig_evo.add_trace(go.Scatter(x=df_evo["data"], y=df_evo["meta_venda"].cumsum(), mode="lines", name="Budget", line=dict(color="#B8923A", width=2, dash="dot")))')
nova.append('            if df_evo["venda_ano1"].sum() > 0:')
nova.append('                fig_evo.add_trace(go.Scatter(x=df_evo["data"], y=df_evo["venda_ano1"].cumsum(), mode="lines", name="Ano Anterior", line=dict(color="#8B7A5A", width=1.5, dash="dash")))')
nova.append('            fig_evo.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=10), xaxis=dict(tickfont=dict(family="Nunito", size=10, color=MARROM)), yaxis=dict(showgrid=True, gridcolor="#E8DCC8", tickfont=dict(family="Nunito", size=10, color=MARROM)), legend=dict(font=dict(family="Nunito", size=11, color=MARROM), orientation="h", yanchor="bottom", y=1.02), font=dict(family="Nunito"), height=300)')
nova.append('            st.plotly_chart(fig_evo, use_container_width=True, key="fig_evo_vd")')
nova.append('')
nova.append('        st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('        col_r1, col_r2 = st.columns(2)')
nova.append('        # Performance vs Budget por filial')
nova.append('        with col_r1:')
nova.append('            with st.container(border=True):')
nova.append('                st.markdown(\'<div class="section-title">Performance vs Budget por Filial</div>\', unsafe_allow_html=True)')
nova.append('                df_rank_vd = df_vd_f.groupby("filial_curta").agg(venda_salao=("venda_salao","sum"), meta_venda=("meta_venda","sum")).reset_index()')
nova.append('                df_rank_vd["pct_meta"] = ((df_rank_vd["venda_salao"]/df_rank_vd["meta_venda"]-1)*100).round(1)')
nova.append('                df_rank_vd = df_rank_vd.sort_values("pct_meta", ascending=True)')
nova.append('                for _, row in df_rank_vd.iterrows():')
nova.append('                    cor_b = "#2e6b3e" if row["pct_meta"] >= 0 else "#c0392b"')
nova.append('                    seta_b = "▲" if row["pct_meta"] >= 0 else "▼"')
nova.append('                    vd_fmt = f"R$ {row[\'venda_salao\']:,.0f}".replace(",",".")')
nova.append('                    st.markdown(f\'<div style="padding:8px 0; border-bottom:1px solid #e8ddc8; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:12px; font-weight:700; color:#3D2B1F;">{row["filial_curta"]}</span><div style="text-align:right;"><div style="font-size:12px; color:#3D2B1F;">{vd_fmt}</div><div style="font-size:12px; color:{cor_b}; font-weight:700;">{seta_b} {row["pct_meta"]:+.1f}% vs Budget</div></div></div>\', unsafe_allow_html=True)')
nova.append('')
nova.append('        # Sazonalidade por dia da semana')
nova.append('        with col_r2:')
nova.append('            with st.container(border=True):')
nova.append('                st.markdown(\'<div class="section-title">Media de Venda por Dia da Semana</div>\', unsafe_allow_html=True)')
nova.append('                ordem_dias = ["seg","ter","qua","qui","sex","sab","dom"]')
nova.append('                labels_dias = ["Seg","Ter","Qua","Qui","Sex","Sab","Dom"]')
nova.append('                df_dow = df_vd[df_vd["ano"] == ano_sel].copy()')
nova.append('                if filial_vd_sel != "Todas":')
nova.append('                    df_dow = df_dow[df_dow["filial_curta"] == filial_vd_sel]')
nova.append('                df_dow["dia_norm"] = df_dow["dia_semana"].str[:3].str.lower()')
nova.append('                df_dow_g = df_dow.groupby("dia_norm")["venda_salao"].mean().reset_index()')
nova.append('                df_dow_g = df_dow_g.set_index("dia_norm").reindex([d for d in ordem_dias if d in df_dow_g["dia_norm"].values]).reset_index()')
nova.append('                df_dow_g["label"] = df_dow_g["dia_norm"].map(dict(zip(ordem_dias, labels_dias)))')
nova.append('                if len(df_dow_g) > 0:')
nova.append('                    fig_dow = go.Figure(go.Bar(x=df_dow_g["label"], y=df_dow_g["venda_salao"], marker_color=[VERDE if v == df_dow_g["venda_salao"].max() else "#B8923A" if v >= df_dow_g["venda_salao"].quantile(0.7) else "#D8CFC0" for v in df_dow_g["venda_salao"]], text=df_dow_g["venda_salao"].apply(lambda v: f"Rk"), textposition="outside", textfont=dict(family="Nunito", size=11, color=MARROM)))')
nova.append('                    fig_dow.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=10), xaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)), yaxis=dict(showgrid=False), font=dict(family="Nunito"), height=280)')
nova.append('                    st.plotly_chart(fig_dow, use_container_width=True, key="fig_dow_vd")')
nova.append('')
nova.append('        st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('        # Comparativo mensal 2025 vs 2026')
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Comparativo Mensal 2025 vs 2026</div>\', unsafe_allow_html=True)')
nova.append('            df_mensal = df_vd.copy()')
nova.append('            if filial_vd_sel != "Todas":')
nova.append('                df_mensal = df_mensal[df_mensal["filial_curta"] == filial_vd_sel]')
nova.append('            df_mensal["mes_num"] = pd.to_datetime(df_mensal["data"]).dt.month')
nova.append('            df_mensal["mes_label"] = pd.to_datetime(df_mensal["data"]).dt.strftime("%b")')
nova.append('            df_2025 = df_mensal[df_mensal["ano"]==2025].groupby(["mes_num","mes_label"])["venda_salao"].sum().reset_index().sort_values("mes_num")')
nova.append('            df_2026 = df_mensal[df_mensal["ano"]==2026].groupby(["mes_num","mes_label"])["venda_salao"].sum().reset_index().sort_values("mes_num")')
nova.append('            fig_mens = go.Figure()')
nova.append('            fig_mens.add_trace(go.Bar(x=df_2025["mes_label"], y=df_2025["venda_salao"], name="2025", marker_color="#8B7A5A", opacity=0.7))')
nova.append('            fig_mens.add_trace(go.Bar(x=df_2026["mes_label"], y=df_2026["venda_salao"], name="2026", marker_color=VERDE))')
nova.append('            fig_mens.update_layout(barmode="group", paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=10), xaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)), yaxis=dict(showgrid=True, gridcolor="#E8DCC8", tickfont=dict(family="Nunito", size=10, color=MARROM)), legend=dict(font=dict(family="Nunito", size=11, color=MARROM), orientation="h", yanchor="bottom", y=1.02), font=dict(family="Nunito"), height=300)')
nova.append('            st.plotly_chart(fig_mens, use_container_width=True, key="fig_mens_vd")')
nova.append('')
nova.append('        st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('        # HDC por filial')
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Produtividade por Assento — Venda por HDC</div>\', unsafe_allow_html=True)')
nova.append('            st.markdown(\'<div style="font-size:12px; color:#8B7A5A; margin-bottom:16px;">Media de venda por assento disponivel. Indica eficiencia de ocupacao e produtividade do salao.</div>\', unsafe_allow_html=True)')
nova.append('            df_hdc = df_vd_f.groupby("filial_curta")["venda_por_hdc"].mean().reset_index().sort_values("venda_por_hdc", ascending=False)')
nova.append('            df_hdc_total = df_hdc["venda_por_hdc"].mean()')
nova.append('            fig_hdc = go.Figure(go.Bar(x=df_hdc["filial_curta"], y=df_hdc["venda_por_hdc"], marker_color=[VERDE if v >= df_hdc_total else "#B8923A" for v in df_hdc["venda_por_hdc"]], text=df_hdc["venda_por_hdc"].apply(lambda v: f"R$ {v:.0f}"), textposition="outside", textfont=dict(family="Nunito", size=12, color=MARROM)))')
nova.append('            fig_hdc.add_hline(y=df_hdc_total, line_dash="dot", line_color="#B8923A", annotation_text=f"Media: R$ {df_hdc_total:.0f}", annotation_font=dict(family="Nunito", size=11, color="#B8923A"))')
nova.append('            fig_hdc.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=40), xaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)), yaxis=dict(showgrid=False), font=dict(family="Nunito"), height=280)')
nova.append('            st.plotly_chart(fig_hdc, use_container_width=True, key="fig_hdc_vd")')

result = lines[:1051] + nova + lines[1170:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print(f'Feito! Total: {len(result)} linhas')
