lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')

nova = []
nova.append('elif aba_sel == "Vendas":')
nova.append('    st.markdown(\'\'\'<div style="font-weight:800; font-size:26px; color:#3D2B1F; letter-spacing:0.08em; text-transform:uppercase; margin-bottom:4px;">Vendas</div>')
nova.append('    <div style="font-size:13px; color:#8B9A2E; letter-spacing:0.1em; margin-bottom:20px;">PERFORMANCE FINANCEIRA</div>\'\'\', unsafe_allow_html=True)')
nova.append('')
nova.append('    visao_sel = st.radio("", ["Operacao Geral", "iFood"], horizontal=True, key="visao_vendas")')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    if visao_sel == "Operacao Geral":')
nova.append('        import calendar')
nova.append('        from datetime import datetime, timedelta')
nova.append('        df_vd = df_vendas_diarias.copy()')
nova.append('        df_vd["data"] = pd.to_datetime(df_vd["data"])')
nova.append('        df_vd["filial_curta"] = df_vd["filial"].str.replace("Olive Garden - ", "", regex=False)')
nova.append('')
nova.append('        # Filtros')
nova.append('        col_f1, col_f2, col_f3 = st.columns(3)')
nova.append('        with col_f1:')
nova.append('            anos = sorted(df_vd["ano"].dropna().unique().astype(int), reverse=True)')
nova.append('            ano_sel = st.selectbox("Ano:", anos, key="ano_vd")')
nova.append('        with col_f2:')
nova.append('            meses_ord = ["jan","fev","mar","abr","mai","jun","jul","ago","set","out","nov","dez"]')
nova.append('            meses_disp = [m for m in meses_ord if m in df_vd[df_vd["ano"]==ano_sel]["mes"].str[:3].str.lower().unique()]')
nova.append('            mes_sel = st.selectbox("Mes:", ["Todos"] + meses_disp, key="mes_vd")')
nova.append('        with col_f3:')
nova.append('            filiais_vd = ["Todas"] + sorted(df_vd["filial_curta"].unique())')
nova.append('            filial_vd_sel = st.selectbox("Filial:", filiais_vd, key="filial_vd")')
nova.append('')
nova.append('        df_vd_f = df_vd[df_vd["ano"] == ano_sel].copy()')
nova.append('        if mes_sel != "Todos":')
nova.append('            df_vd_f = df_vd_f[df_vd_f["mes"].str[:3].str.lower() == mes_sel]')
nova.append('        if filial_vd_sel != "Todas":')
nova.append('            df_vd_f = df_vd_f[df_vd_f["filial_curta"] == filial_vd_sel]')
nova.append('')
nova.append('        # Cards executivos')
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Visao Executiva</div>\', unsafe_allow_html=True)')
nova.append('            vt = df_vd_f["venda_total"].sum()')
nova.append('            mt = df_vd_f["meta_venda"].sum()')
nova.append('            va1 = df_vd_f["venda_ano1"].sum()')
nova.append('            gc = df_vd_f["gc_salao"].sum()')
nova.append('            tk = vt / gc if gc > 0 else 0')
nova.append('            pct_meta = (vt/mt - 1)*100 if mt > 0 else 0')
nova.append('            pct_ano1 = (vt/va1 - 1)*100 if va1 > 0 else 0')
nova.append('            vt_fmt = f"R$ {vt:,.0f}".replace(",",".")')
nova.append('            mt_fmt = f"R$ {mt:,.0f}".replace(",",".")')
nova.append('            va1_fmt = f"R$ {va1:,.0f}".replace(",",".")')
nova.append('            tk_fmt = f"R$ {tk:.0f}"')
nova.append('            cor_meta = "#2e6b3e" if pct_meta >= 0 else VERMELHO')
nova.append('            cor_ano1 = "#2e6b3e" if pct_ano1 >= 0 else VERMELHO')
nova.append('            cols_c = st.columns(5)')
nova.append('            cards = [')
nova.append('                ("VENDA TOTAL", vt_fmt, None, None),')
nova.append('                ("BUDGET", mt_fmt, f"{pct_meta:+.1f}%", cor_meta),')
nova.append('                ("ANO ANTERIOR", va1_fmt, f"{pct_ano1:+.1f}%", cor_ano1),')
nova.append('                ("GUEST COUNT", f"{int(gc):,}".replace(",","."), None, None),')
nova.append('                ("TICKET MEDIO", tk_fmt, None, None),')
nova.append('            ]')
nova.append('            for col_c, (label, valor, delta, cor_d) in zip(cols_c, cards):')
nova.append('                with col_c:')
nova.append('                    delta_html = f\'<div style="font-size:11px; color:{cor_d}; font-weight:700;">{delta}</div>\' if delta else ""')
nova.append('                    st.markdown(f\'\'\'<div style="background:#3D2B1F; border-radius:10px; padding:16px; color:#F5F0E8;">') 
nova.append('                        <div style="font-size:9px; color:#D8CFC0; letter-spacing:2px; margin-bottom:8px;">{label}</div>')
nova.append('                        <div style="font-size:16px; font-weight:700; margin-bottom:4px;">{valor}</div>')
nova.append('                        {delta_html}</div>\'\'\', unsafe_allow_html=True)')
nova.append('')
nova.append('        st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('        # Evolucao diaria')
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Evolucao de Venda</div>\', unsafe_allow_html=True)')
nova.append('            df_evo = df_vd_f.groupby("data").agg(venda_total=("venda_total","sum"), meta_venda=("meta_venda","sum"), venda_ano1=("venda_ano1","sum")).reset_index().sort_values("data")')
nova.append('            fig_evo = go.Figure()')
nova.append('            fig_evo.add_trace(go.Scatter(x=df_evo["data"], y=df_evo["venda_total"].cumsum(), mode="lines", name="Realizado", line=dict(color=VERDE, width=3)))')
nova.append('            fig_evo.add_trace(go.Scatter(x=df_evo["data"], y=df_evo["meta_venda"].cumsum(), mode="lines", name="Budget", line=dict(color="#B8923A", width=2, dash="dot")))')
nova.append('            if df_evo["venda_ano1"].sum() > 0:')
nova.append('                fig_evo.add_trace(go.Scatter(x=df_evo["data"], y=df_evo["venda_ano1"].cumsum(), mode="lines", name="Ano Anterior", line=dict(color="#8B7A5A", width=1.5, dash="dash")))')
nova.append('            fig_evo.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=10), xaxis=dict(tickfont=dict(family="Nunito", size=10, color=MARROM)), yaxis=dict(showgrid=True, gridcolor="#E8DCC8", tickfont=dict(family="Nunito", size=10, color=MARROM)), legend=dict(font=dict(family="Nunito", size=11, color=MARROM), orientation="h", yanchor="bottom", y=1.02), font=dict(family="Nunito"), height=320)')
nova.append('            st.plotly_chart(fig_evo, use_container_width=True, key="fig_evo_vd")')
nova.append('')
nova.append('        st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('        col_r1, col_r2 = st.columns(2)')
nova.append('        # Ranking por filial')
nova.append('        with col_r1:')
nova.append('            with st.container(border=True):')
nova.append('                st.markdown(\'<div class="section-title">Ranking por Filial</div>\', unsafe_allow_html=True)')
nova.append('                df_rank_vd = df_vd_f.groupby("filial_curta").agg(venda_total=("venda_total","sum"), meta_venda=("meta_venda","sum")).reset_index()')
nova.append('                df_rank_vd["pct_meta"] = ((df_rank_vd["venda_total"]/df_rank_vd["meta_venda"]-1)*100).round(1)')
nova.append('                df_rank_vd = df_rank_vd.sort_values("venda_total", ascending=True)')
nova.append('                df_rank_vd["vt_fmt"] = df_rank_vd["venda_total"].apply(lambda v: f"R$ {v:,.0f}".replace(",","."))')
nova.append('                fig_rank_vd = go.Figure(go.Bar(y=df_rank_vd["filial_curta"], x=df_rank_vd["venda_total"], orientation="h", marker_color=[VERDE if v>=0 else VERMELHO for v in df_rank_vd["pct_meta"]], text=df_rank_vd["vt_fmt"], textposition="inside", textfont=dict(family="Nunito", size=11, color="white")))')
nova.append('                fig_rank_vd.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=10), xaxis=dict(showgrid=False), yaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)), font=dict(family="Nunito"), height=280)')
nova.append('                st.plotly_chart(fig_rank_vd, use_container_width=True, key="fig_rank_vd2")')
nova.append('')
nova.append('        # Mix de canal')
nova.append('        with col_r2:')
nova.append('            with st.container(border=True):')
nova.append('                st.markdown(\'<div class="section-title">Mix de Canal</div>\', unsafe_allow_html=True)')
nova.append('                pct_salao = df_vd_f["pct_salao"].mean()*100 if df_vd_f["pct_salao"].notna().any() else 0')
nova.append('                pct_dlv = df_vd_f["pct_dlv"].mean()*100 if df_vd_f["pct_dlv"].notna().any() else 0')
nova.append('                pct_togo = df_vd_f["pct_togo"].mean()*100 if df_vd_f["pct_togo"].notna().any() else 0')
nova.append('                fig_mix = go.Figure(go.Pie(labels=["Salao","Delivery","ToGo"], values=[pct_salao, pct_dlv, pct_togo], hole=0.5, textinfo="label+percent", textfont=dict(family="Nunito", size=12), marker=dict(colors=[VERDE,"#B8923A","#3D7A5C"])))')
nova.append('                fig_mix.update_layout(paper_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=10), legend=dict(font=dict(family="Nunito", size=11, color=MARROM)), font=dict(family="Nunito"), height=280)')
nova.append('                st.plotly_chart(fig_mix, use_container_width=True, key="fig_mix_vd")')
nova.append('')
nova.append('    elif visao_sel == "iFood":')
nova.append('        import calendar')
nova.append('        from datetime import datetime')
nova.append('        df_v = df_ifood_vendas[df_ifood_vendas["logistica"] == "Entrega parceira"].copy()')
nova.append('        df_v["filial_curta"] = df_v["filial"].str.replace("Olive Garden - ", "", regex=False)')
nova.append('        periodos = sorted(df_v["periodo"].unique())')
nova.append('')
nova.append('        # Cards executivos')
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Visao Executiva</div>\', unsafe_allow_html=True)')
nova.append('            cols_v = st.columns(len(periodos))')
nova.append('            prev_fat = None')
nova.append('            for idx, periodo in enumerate(periodos):')
nova.append('                df_per = df_v[df_v["periodo"] == periodo]')
nova.append('                fat = df_per["faturamento"].sum()')
nova.append('                ped = int(df_per["pedidos"].sum())')
nova.append('                tkt = fat / ped if ped > 0 else 0')
nova.append('                nov = int(df_per["novos_clientes"].sum())')
nova.append('                mes = periodo.split("/")[1].strip()[:2] if "/" in periodo else periodo[:3]')
nova.append('                mes_map = {"01":"Jan","02":"Fev","03":"Mar","04":"Abr","05":"Mai","06":"Jun","07":"Jul","08":"Ago","09":"Set","10":"Out","11":"Nov","12":"Dez"}')
nova.append('                mes_label = mes_map.get(mes, periodo)')
nova.append('                delta_txt = f" (+{((fat/prev_fat-1)*100):.1f}%)" if prev_fat and prev_fat > 0 else ""')
nova.append('                prev_fat = fat')
nova.append('                fat_fmt = f"R$ {fat:,.0f}".replace(",",".")')
nova.append('                tkt_fmt = f"R$ {tkt:.0f}"')
nova.append('                proj_html = ""')
nova.append('                try:')
nova.append('                    partes = periodo.split("-")')
nova.append('                    d_ini = datetime.strptime(partes[0].strip(), "%d/%m/%Y")')
nova.append('                    d_fim = datetime.strptime(partes[1].strip(), "%d/%m/%Y")')
nova.append('                    dias_dec = (d_fim - d_ini).days + 1')
nova.append('                    dias_mes = calendar.monthrange(d_ini.year, d_ini.month)[1]')
nova.append('                    if dias_dec < dias_mes:')
nova.append('                        fat_proj = fat / dias_dec * dias_mes')
nova.append('                        fat_proj_fmt = f"R$ {fat_proj:,.0f}".replace(",",".")')
nova.append('                        ped_proj = int(ped / dias_dec * dias_mes)')
nova.append('                        proj_html = f\'\'\'<div style="margin-top:12px; padding-top:10px; border-top:1px solid rgba(255,255,255,0.1);">')
nova.append('                            <div style="font-size:9px; color:#B8923A; letter-spacing:2px; margin-bottom:6px;">PROJECAO MES COMPLETO ({dias_mes} dias)</div>')
nova.append('                            <div style="display:grid; grid-template-columns:1fr 1fr; gap:10px;">')
nova.append('                            <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:2px;">FATURAMENTO</div>')
nova.append('                            <div style="font-size:14px; font-weight:700; color:#B8923A;">{fat_proj_fmt}</div></div>')
nova.append('                            <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:2px;">PEDIDOS</div>')
nova.append('                            <div style="font-size:14px; font-weight:700; color:#B8923A;">{ped_proj:,}</div></div>')
nova.append('                            </div>')
nova.append('                            <div style="font-size:9px; color:#8B7A5A; margin-top:4px;">Parcial: {dias_dec} de {dias_mes} dias</div>')
nova.append('                            </div>\'\'\'')
nova.append('                except:')
nova.append('                    pass')
nova.append('                with cols_v[idx]:')
nova.append('                    st.markdown(f\'\'\'<div style="background:#3D2B1F; border-radius:12px; padding:20px; color:#F5F0E8; margin-bottom:8px;">')
nova.append('                        <div style="font-size:10px; letter-spacing:3px; color:#8B9A2E; text-transform:uppercase; margin-bottom:14px;">{mes_label}{delta_txt}</div>')
nova.append('                        <div style="display:grid; grid-template-columns:1fr 1fr; gap:14px;">')
nova.append('                        <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:4px;">FATURAMENTO</div>')
nova.append('                        <div style="font-size:16px; font-weight:700;">{fat_fmt}</div></div>')
nova.append('                        <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:4px;">PEDIDOS</div>')
nova.append('                        <div style="font-size:16px; font-weight:700;">{ped:,}</div></div>')
nova.append('                        <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:4px;">TICKET MEDIO</div>')
nova.append('                        <div style="font-size:16px; font-weight:700; color:#8B9A2E;">{tkt_fmt}</div></div>')
nova.append('                        <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:4px;">NOVOS CLIENTES</div>')
nova.append('                        <div style="font-size:16px; font-weight:700; color:#8B9A2E;">{nov:,}</div></div>')
nova.append('                        </div>{proj_html}</div>\'\'\', unsafe_allow_html=True)')
nova.append('')
nova.append('        st.markdown("<br>", unsafe_allow_html=True)')
nova.append('        periodo_sel_v = st.selectbox("Periodo:", periodos, index=len(periodos)-1, key="periodo_v")')
nova.append('        df_vp = df_v[df_v["periodo"] == periodo_sel_v]')
nova.append('')
nova.append('        # Ranking por filial com projecao')
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Faturamento por Filial</div>\', unsafe_allow_html=True)')
nova.append('            df_rank = df_vp.groupby("filial_curta").agg(faturamento=("faturamento","sum"), pedidos=("pedidos","sum"), novos_clientes=("novos_clientes","sum")).reset_index()')
nova.append('            df_rank["ticket_medio"] = (df_rank["faturamento"] / df_rank["pedidos"]).round(0)')
nova.append('            df_rank = df_rank.sort_values("faturamento", ascending=True)')
nova.append('            df_rank["fat_fmt"] = df_rank["faturamento"].apply(lambda v: f"R$ {v:,.0f}".replace(",","."))')
nova.append('            is_parcial = False')
nova.append('            dias_decorridos = 30')
nova.append('            dias_no_mes = 30')
nova.append('            try:')
nova.append('                partes = periodo_sel_v.split("-")')
nova.append('                d_ini = datetime.strptime(partes[0].strip(), "%d/%m/%Y")')
nova.append('                d_fim = datetime.strptime(partes[1].strip(), "%d/%m/%Y")')
nova.append('                dias_decorridos = (d_fim - d_ini).days + 1')
nova.append('                dias_no_mes = calendar.monthrange(d_ini.year, d_ini.month)[1]')
nova.append('                if dias_decorridos < dias_no_mes:')
nova.append('                    is_parcial = True')
nova.append('                    df_rank["faturamento_projetado"] = (df_rank["faturamento"] / dias_decorridos * dias_no_mes).round(0)')
nova.append('                    df_rank["proj_fmt"] = df_rank["faturamento_projetado"].apply(lambda v: f"R$ {v:,.0f}".replace(",","."))')
nova.append('            except:')
nova.append('                pass')
nova.append('            fig_rank = go.Figure()')
nova.append('            if is_parcial:')
nova.append('                fig_rank.add_trace(go.Bar(y=df_rank["filial_curta"], x=df_rank["faturamento_projetado"], orientation="h", name=f"Projetado ({dias_no_mes} dias)", marker_color="#B8923A", opacity=0.4, text=df_rank["proj_fmt"], textposition="inside", textfont=dict(family="Nunito", size=12, color="white")))')
nova.append('            fig_rank.add_trace(go.Bar(y=df_rank["filial_curta"], x=df_rank["faturamento"], orientation="h", name=f"Realizado ({dias_decorridos} dias)" if is_parcial else "Faturamento", marker_color=VERDE, text=df_rank["fat_fmt"], textposition="inside", textfont=dict(family="Nunito", size=12, color="white")))')
nova.append('            if is_parcial:')
nova.append('                fig_rank.add_annotation(text=f"Parcial: {dias_decorridos} de {dias_no_mes} dias | Projecao linear", xref="paper", yref="paper", x=0.5, y=-0.08, showarrow=False, font=dict(family="Nunito", size=11, color="#B8923A"))')
nova.append('            fig_rank.update_layout(barmode="overlay", paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=40,b=30,l=10,r=200), xaxis=dict(showgrid=False, tickfont=dict(family="Nunito", size=11, color=MARROM)), yaxis=dict(tickfont=dict(family="Nunito", size=12, color=MARROM)), legend=dict(font=dict(family="Nunito", size=11, color=MARROM), orientation="h", yanchor="bottom", y=1.04), font=dict(family="Nunito"), height=320)')
nova.append('            st.plotly_chart(fig_rank, use_container_width=True, key="fig_rank_v")')
nova.append('')
nova.append('        st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('        # Evolucao de receita iFood')
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Evolucao de Receita iFood</div>\', unsafe_allow_html=True)')
nova.append('            evolucao = []')
nova.append('            for p in periodos:')
nova.append('                df_p = df_v[df_v["periodo"] == p]')
nova.append('                fat_p = df_p["faturamento"].sum()')
nova.append('                try:')
nova.append('                    partes = p.split("-")')
nova.append('                    d_ini = datetime.strptime(partes[0].strip(), "%d/%m/%Y")')
nova.append('                    d_fim = datetime.strptime(partes[1].strip(), "%d/%m/%Y")')
nova.append('                    dias_dec = (d_fim - d_ini).days + 1')
nova.append('                    dias_mes = calendar.monthrange(d_ini.year, d_ini.month)[1]')
nova.append('                    mes_map2 = {"01":"Jan","02":"Fev","03":"Mar","04":"Abr","05":"Mai","06":"Jun","07":"Jul","08":"Ago","09":"Set","10":"Out","11":"Nov","12":"Dez"}')
nova.append('                    mes_label2 = mes_map2.get(f"{d_ini.month:02d}", p)')
nova.append('                    is_p = dias_dec < dias_mes')
nova.append('                    fat_proj2 = fat_p / dias_dec * dias_mes if is_p else None')
nova.append('                    evolucao.append({"mes": mes_label2, "fat": fat_p, "proj": fat_proj2, "parcial": is_p})')
nova.append('                except:')
nova.append('                    evolucao.append({"mes": p[:3], "fat": fat_p, "proj": None, "parcial": False})')
nova.append('            fig_evo2 = go.Figure()')
nova.append('            meses2 = [e["mes"] for e in evolucao]')
nova.append('            fats2 = [e["fat"] for e in evolucao]')
nova.append('            fig_evo2.add_trace(go.Scatter(x=meses2, y=fats2, mode="lines+markers+text", name="Realizado", line=dict(color=VERDE, width=3), marker=dict(size=10, color=VERDE), text=[f"R$ {v:,.0f}".replace(",",".") for v in fats2], textposition="top center", textfont=dict(family="Nunito", size=11, color=VERDE)))')
nova.append('            for i_e, e in enumerate(evolucao):')
nova.append('                if e["parcial"] and e["proj"]:')
nova.append('                    fig_evo2.add_trace(go.Scatter(x=[meses2[i_e], meses2[i_e]], y=[fats2[i_e], e["proj"]], mode="lines+markers+text", name="Projetado", line=dict(color="#B8923A", width=2, dash="dot"), marker=dict(size=10, color="#B8923A", symbol="diamond"), text=["", f"R$ {e[\'proj\']:,.0f}".replace(",",".")], textposition="top center", textfont=dict(family="Nunito", size=11, color="#B8923A"), showlegend=True))')
nova.append('            fig_evo2.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=30,b=10,l=10,r=10), xaxis=dict(tickfont=dict(family="Nunito", size=12, color=MARROM), showgrid=False), yaxis=dict(showgrid=True, gridcolor="#E8DCC8", tickfont=dict(family="Nunito", size=11, color=MARROM)), legend=dict(font=dict(family="Nunito", size=11, color=MARROM), orientation="h", yanchor="bottom", y=1.02), font=dict(family="Nunito"), height=350)')
nova.append('            st.plotly_chart(fig_evo2, use_container_width=True, key="fig_evo_v2")')
nova.append('')
nova.append('        st.markdown("<br>", unsafe_allow_html=True)')
nova.append('        col_h1, col_h2 = st.columns(2)')
nova.append('        with col_h1:')
nova.append('            with st.container(border=True):')
nova.append('                st.markdown(\'<div class="section-title">Horario de Pico</div>\', unsafe_allow_html=True)')
nova.append('                df_hor = df_ifood_horarios[df_ifood_horarios["periodo"] == periodo_sel_v].groupby(["periodo_semana","horario"])["pedidos"].sum().reset_index()')
nova.append('                if len(df_hor) > 0:')
nova.append('                    df_hor_piv = df_hor.pivot(index="horario", columns="periodo_semana", values="pedidos").fillna(0)')
nova.append('                    fig_hor = go.Figure(data=go.Heatmap(z=df_hor_piv.values, x=df_hor_piv.columns.tolist(), y=df_hor_piv.index.tolist(), colorscale=[[0,"#F5F0E8"],[0.5,"#B8923A"],[1,VERDE]], texttemplate="%{z:.0f}", textfont=dict(family="Nunito", size=11)))')
nova.append('                    fig_hor.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=10), xaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)), yaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)), font=dict(family="Nunito"), height=380, coloraxis_showscale=False)')
nova.append('                    st.plotly_chart(fig_hor, use_container_width=True, key="fig_hor_v")')
nova.append('        with col_h2:')
nova.append('            with st.container(border=True):')
nova.append('                st.markdown(\'<div class="section-title">Dias de Pico</div>\', unsafe_allow_html=True)')
nova.append('                ordem_dias = ["Segunda","Terca","Quarta","Quinta","Sexta","Sabado","Domingo"]')
nova.append('                df_dias = df_ifood_dias[df_ifood_dias["periodo"] == periodo_sel_v].copy()')
nova.append('                df_dias["dia_norm"] = df_dias["dia_semana"].str.normalize("NFKD").str.encode("ascii","ignore").str.decode("ascii").str.strip()')
nova.append('                df_dias_g = df_dias.groupby("dia_norm")["pedidos"].sum().reset_index()')
nova.append('                df_dias_ord = [d for d in ordem_dias if d in df_dias_g["dia_norm"].values]')
nova.append('                df_dias_g = df_dias_g.set_index("dia_norm").reindex(df_dias_ord).reset_index()')
nova.append('                if len(df_dias_g) > 0:')
nova.append('                    fig_dias = go.Figure(go.Bar(x=df_dias_g["dia_norm"], y=df_dias_g["pedidos"], marker_color=VERDE, text=df_dias_g["pedidos"], textposition="outside", textfont=dict(family="Nunito", size=12, color=MARROM)))')
nova.append('                    fig_dias.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=10), xaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)), yaxis=dict(showgrid=False, tickfont=dict(family="Nunito", size=11, color=MARROM)), font=dict(family="Nunito"), height=380)')
nova.append('                    st.plotly_chart(fig_dias, use_container_width=True, key="fig_dias_v")')
nova.append('        st.markdown("<br>", unsafe_allow_html=True)')
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Mix de Pagamento</div>\', unsafe_allow_html=True)')
nova.append('            df_pag = df_ifood_pagamentos[df_ifood_pagamentos["periodo"] == periodo_sel_v].groupby("forma_pagamento")["pedidos"].sum().reset_index().sort_values("pedidos", ascending=False)')
nova.append('            if len(df_pag) > 0:')
nova.append('                fig_pag = go.Figure(go.Pie(labels=df_pag["forma_pagamento"], values=df_pag["pedidos"], hole=0.5, textinfo="label+percent", textfont=dict(family="Nunito", size=12), marker=dict(colors=[VERDE,"#B8923A","#3D7A5C","#7A3D3D","#3D5A7A","#7A5C3D","#5C7A3D","#7A6B3D"])))')
nova.append('                fig_pag.update_layout(paper_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=10), legend=dict(font=dict(family="Nunito", size=11, color=MARROM)), font=dict(family="Nunito"), height=320)')
nova.append('                st.plotly_chart(fig_pag, use_container_width=True, key="fig_pag_v")')

result = lines[:1044] + nova + lines[1293:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print(f'Feito! Total: {len(result)} linhas')
