lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')
for i, line in enumerate(lines):
    if 'OLIVE GARDEN BRAND INTELLIGENCE' in line:
        footer_line = i - 1
        break

nova = []
nova.append('elif aba_sel == "Correlacoes":')
nova.append('    st.markdown(')
nova.append('        \'\'\'<div style="font-weight:800; font-size:26px; color:#3D2B1F; letter-spacing:0.08em; text-transform:uppercase; margin-bottom:4px;">Correlacoes & Tendencias</div>')
nova.append('        <div style="font-size:13px; color:#8B9A2E; letter-spacing:0.1em; margin-bottom:20px;">PADROES DE COMPORTAMENTO E ANALISE PREDITIVA</div>\'\'\',')
nova.append('        unsafe_allow_html=True')
nova.append('    )')
nova.append('')
nova.append('    # Prepara dados')
nova.append('    df_perf_c = df_perf[df_perf["restaurant"] != "nan"].copy()')
nova.append('    df_perf_c["filial_curta"] = df_perf_c["restaurant"].str.replace("Olive Garden - ", "")')
nova.append('    df_perf_c["periodo_curto"] = df_perf_c["periodo"].str.extract(r"(FW\d+ to FW\d+)")')
nova.append('')
nova.append('    # Score de Risco por Filial')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Score de Risco por Filial</div>\', unsafe_allow_html=True)')
nova.append('        st.markdown(\'<div style="font-size:12px; color:#8B7A5A; margin-bottom:16px;">Combinacao de tendencia GSS + reputacao publica. Quanto maior o score, maior o risco de deterioracao.</div>\', unsafe_allow_html=True)')
nova.append('')
nova.append('        rep_pub = df.groupby("filial").agg(')
nova.append('            nota_media=("nota", "mean"),')
nova.append('            pct_pos=("sentimento", lambda x: (x == "Positivo").sum() / len(x) * 100)')
nova.append('        ).reset_index()')
nova.append('        rep_pub["score_externo"] = (((rep_pub["nota_media"] - 1) / 4) * 40 + rep_pub["pct_pos"] * 0.6).clip(0, 100).round(1)')
nova.append('        rep_pub["filial_curta"] = rep_pub["filial"].str.replace("Olive Garden - ", "")')
nova.append('')
nova.append('        if len(df_perf_c) > 0:')
nova.append('            gss_atual = df_perf_c.sort_values("periodo_curto").groupby("filial_curta").last().reset_index()')
nova.append('            merged = rep_pub.merge(gss_atual[["filial_curta", "overall_experience"]], on="filial_curta", how="left")')
nova.append('            merged["score_risco"] = (100 - merged["score_externo"]) * 0.5 + (100 - merged["overall_experience"].fillna(80)) * 0.5')
nova.append('            merged = merged.sort_values("score_risco", ascending=False)')
nova.append('')
nova.append('            fig_risco = go.Figure()')
nova.append('            cores_risco = ["#c0392b" if v > 20 else "#B8923A" if v > 12 else VERDE for v in merged["score_risco"]]')
nova.append('            fig_risco.add_trace(go.Bar(')
nova.append('                x=merged["filial_curta"],')
nova.append('                y=merged["score_risco"].round(1),')
nova.append('                marker_color=cores_risco,')
nova.append('                text=merged["score_risco"].round(1),')
nova.append('                textposition="outside",')
nova.append('                textfont=dict(family="Nunito", size=12),')
nova.append('            ))')
nova.append('            fig_risco.update_layout(')
nova.append('                paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",')
nova.append('                margin=dict(t=10, b=10, l=10, r=10),')
nova.append('                xaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)),')
nova.append('                yaxis=dict(title="Score de Risco", showgrid=False),')
nova.append('                font=dict(family="Nunito"),')
nova.append('                height=320,')
nova.append('            )')
nova.append('            st.plotly_chart(fig_risco, use_container_width=True, key="fig_risco")')
nova.append('')
nova.append('            for _, row in merged.iterrows():')
nova.append('                if row["score_risco"] > 20:')
nova.append('                    cor = "#c0392b"; icone = "ALTO RISCO"')
nova.append('                elif row["score_risco"] > 12:')
nova.append('                    cor = "#B8923A"; icone = "ATENCAO"')
nova.append('                else:')
nova.append('                    cor = "#2e6b3e"; icone = "SAUDAVEL"')
nova.append('                st.markdown(f\'<div style="padding:6px 0; border-bottom:1px solid #e8ddc8; display:flex; justify-content:space-between;"><span style="font-size:12px; color:{cor}; font-weight:700;">{icone} — {row["filial_curta"]}</span><span style="font-size:12px; color:#3D2B1F;">Reputacao: {row["score_externo"]:.1f} | GSS: {row["overall_experience"]:.1f}% | Risco: {row["score_risco"]:.1f}</span></div>\', unsafe_allow_html=True)')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    # Correlacao GSS vs Reputacao')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Correlacao GSS vs Reputacao Publica</div>\', unsafe_allow_html=True)')
nova.append('        st.markdown(\'<div style="font-size:12px; color:#8B7A5A; margin-bottom:16px;">Cada ponto representa uma filial. A linha de tendencia indica se satisfacao interna e reputacao publica estao alinhadas.</div>\', unsafe_allow_html=True)')
nova.append('        if len(df_perf_c) > 0 and len(rep_pub) > 0:')
nova.append('            scatter_df = rep_pub.merge(gss_atual[["filial_curta", "overall_experience", "taste", "service", "value"]], on="filial_curta", how="left").dropna()')
nova.append('            fig_scatter = go.Figure()')
nova.append('            fig_scatter.add_trace(go.Scatter(')
nova.append('                x=scatter_df["overall_experience"],')
nova.append('                y=scatter_df["score_externo"],')
nova.append('                mode="markers+text",')
nova.append('                text=scatter_df["filial_curta"],')
nova.append('                textposition="top center",')
nova.append('                textfont=dict(family="Nunito", size=11, color=MARROM),')
nova.append('                marker=dict(size=16, color=VERDE, opacity=0.8),')
nova.append('            ))')
nova.append('            fig_scatter.update_layout(')
nova.append('                paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",')
nova.append('                margin=dict(t=10, b=10, l=10, r=10),')
nova.append('                xaxis=dict(title="GSS — Experiencia Geral (% Topbox)", tickfont=dict(family="Nunito", size=11, color=MARROM), gridcolor="#E8DCC8"),')
nova.append('                yaxis=dict(title="Reputacao Publica (Indice)", tickfont=dict(family="Nunito", size=11, color=MARROM), gridcolor="#E8DCC8"),')
nova.append('                font=dict(family="Nunito"),')
nova.append('                height=380,')
nova.append('            )')
nova.append('            st.plotly_chart(fig_scatter, use_container_width=True, key="fig_scatter")')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    # Tendencia GSS por dimensao')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Tendencia GSS por Dimensao — Rede Consolidada</div>\', unsafe_allow_html=True)')
nova.append('        st.markdown(\'<div style="font-size:12px; color:#8B7A5A; margin-bottom:16px;">Evolucao media de cada dimensao considerando todas as filiais. Dimensoes em queda requerem atencao imediata.</div>\', unsafe_allow_html=True)')
nova.append('        if len(df_perf_c["periodo_curto"].dropna().unique()) > 1:')
nova.append('            metricas_t = {"overall_experience": "Exp. Geral", "value": "Valor", "service": "Atendimento", "taste": "Sabor", "speed_of_service": "Velocidade", "clean": "Limpeza", "soup_salad_refill": "Refil Sopa", "breadstick_refill": "Refil Bread"}')
nova.append('            trend_df = df_perf_c.groupby("periodo_curto")[list(metricas_t.keys())].mean().reset_index().sort_values("periodo_curto")')
nova.append('            fig_trend = go.Figure()')
nova.append('            for col, lbl in metricas_t.items():')
nova.append('                delta = trend_df[col].iloc[-1] - trend_df[col].iloc[0] if len(trend_df) > 1 else 0')
nova.append('                cor_line = "#c0392b" if delta < -1 else VERDE if delta > 1 else "#B8923A"')
nova.append('                fig_trend.add_trace(go.Scatter(')
nova.append('                    x=trend_df["periodo_curto"],')
nova.append('                    y=trend_df[col].round(1),')
nova.append('                    mode="lines+markers+text",')
nova.append('                    name=f"{lbl} ({delta:+.1f}%)",')
nova.append('                    line=dict(color=cor_line, width=2),')
nova.append('                    marker=dict(size=8),')
nova.append('                    text=trend_df[col].round(1).astype(str) + "%",')
nova.append('                    textposition="top center",')
nova.append('                    textfont=dict(family="Nunito", size=10),')
nova.append('                ))')
nova.append('            fig_trend.update_layout(')
nova.append('                paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",')
nova.append('                margin=dict(t=20, b=10, l=10, r=10),')
nova.append('                legend=dict(font=dict(family="Nunito", size=10, color=MARROM), orientation="h", yanchor="bottom", y=1.02),')
nova.append('                xaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)),')
nova.append('                yaxis=dict(title="% Topbox", range=[60, 105], showgrid=True, gridcolor="#E8DCC8", tickfont=dict(family="Nunito", size=11, color=MARROM)),')
nova.append('                font=dict(family="Nunito"),')
nova.append('                height=420,')
nova.append('            )')
nova.append('            st.plotly_chart(fig_trend, use_container_width=True, key="fig_trend")')
nova.append('')

result = lines[:footer_line-1] + nova + lines[footer_line-1:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print('Feito! Linhas:', len(result))
