lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')

nova = []
nova.append('elif aba_sel == "Vendas":')
nova.append('    st.markdown(\'\'\'<div style="font-weight:800; font-size:26px; color:#3D2B1F; letter-spacing:0.08em; text-transform:uppercase; margin-bottom:4px;">Vendas</div><div style="font-size:13px; color:#8B9A2E; letter-spacing:0.1em; margin-bottom:20px;">PERFORMANCE FINANCEIRA — iFOOD</div>\'\'\', unsafe_allow_html=True)')
nova.append('')
nova.append('    df_v = df_ifood_vendas[df_ifood_vendas["logistica"] == "Entrega parceira"].copy()')
nova.append('    df_v["filial_curta"] = df_v["filial"].str.replace("Olive Garden - ", "", regex=False)')
nova.append('    periodos = sorted(df_v["periodo"].unique())')
nova.append('    mes_map = {"01": "Jan","02": "Fev","03": "Mar","04": "Abr","05": "Mai","06": "Jun","07": "Jul","08": "Ago","09": "Set","10": "Out","11": "Nov","12": "Dez"}')
nova.append('    def fmt_periodo(p):')
nova.append('        try: return mes_map.get(p.split("/")[1].strip()[:2], p)')
nova.append('        except: return p')
nova.append('')
nova.append('    # Cards executivos')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Visao Executiva</div>\', unsafe_allow_html=True)')
nova.append('        cols_v = st.columns(len(periodos))')
nova.append('        prev_fat = None')
nova.append('        for idx, periodo in enumerate(periodos):')
nova.append('            df_per = df_v[df_v["periodo"] == periodo]')
nova.append('            fat = df_per["faturamento"].sum()')
nova.append('            ped = int(df_per["pedidos"].sum())')
nova.append('            tkt = fat / ped if ped > 0 else 0')
nova.append('            nov = int(df_per["novos_clientes"].sum())')
nova.append('            delta = f" (+{((fat/prev_fat-1)*100):.1f}%)" if prev_fat and prev_fat > 0 else ""')
nova.append('            prev_fat = fat')
nova.append('            with cols_v[idx]:')
nova.append('                st.markdown(f\'\'\'<div style="background:#3D2B1F; border-radius:12px; padding:20px; color:#F5F0E8; margin-bottom:8px;">')
nova.append('                    <div style="font-size:10px; letter-spacing:3px; color:#8B9A2E; text-transform:uppercase; margin-bottom:14px;">{fmt_periodo(periodo)}{delta}</div>')
nova.append('                    <div style="display:grid; grid-template-columns:1fr 1fr; gap:14px;">')
nova.append('                    <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:4px;">FATURAMENTO</div><div style="font-size:18px; font-weight:700;">R</div></div>')
nova.append('                    <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:4px;">PEDIDOS</div><div style="font-size:18px; font-weight:700;">{ped:,}</div></div>')
nova.append('                    <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:4px;">TICKET MEDIO</div><div style="font-size:18px; font-weight:700; color:#8B9A2E;">R</div></div>')
nova.append('                    <div><div style="font-size:9px; color:#D8CFC0; margin-bottom:4px;">NOVOS CLIENTES</div><div style="font-size:18px; font-weight:700; color:#8B9A2E;">{nov:,}</div></div>')
nova.append('                    </div></div>\'\'\', unsafe_allow_html=True)')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    # Seletor de periodo')
nova.append('    periodo_sel_v = st.selectbox("Periodo:", periodos, index=len(periodos)-1, key="periodo_v")')
nova.append('    df_vp = df_v[df_v["periodo"] == periodo_sel_v]')
nova.append('')
nova.append('    # Ranking por filial')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Faturamento por Filial</div>\', unsafe_allow_html=True)')
nova.append('        df_rank = df_vp.groupby("filial_curta").agg(faturamento=("faturamento","sum"), pedidos=("pedidos","sum"), novos_clientes=("novos_clientes","sum")).reset_index()')
nova.append('        df_rank["ticket_medio"] = df_rank["faturamento"] / df_rank["pedidos"]')
nova.append('        df_rank = df_rank.sort_values("faturamento", ascending=True)')
nova.append('        fig_rank = go.Figure()')
nova.append('        fig_rank.add_trace(go.Bar(')
nova.append('            y=df_rank["filial_curta"],')
nova.append('            x=df_rank["faturamento"],')
nova.append('            orientation="h",')
nova.append('            marker_color=VERDE,')
nova.append('            text=df_rank["faturamento"].apply(lambda x: f"R"),')
nova.append('            textposition="outside",')
nova.append('            textfont=dict(family="Nunito", size=12, color=MARROM),')
nova.append('        ))')
nova.append('        fig_rank.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=120), xaxis=dict(showgrid=False, tickfont=dict(family="Nunito", size=11, color=MARROM)), yaxis=dict(tickfont=dict(family="Nunito", size=12, color=MARROM)), font=dict(family="Nunito"), height=280)')
nova.append('        st.plotly_chart(fig_rank, use_container_width=True, key="fig_rank_v")')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    col_h1, col_h2 = st.columns(2)')
nova.append('')
nova.append('    # Horario de pico')
nova.append('    with col_h1:')
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Horario de Pico</div>\', unsafe_allow_html=True)')
nova.append('            df_hor = df_ifood_horarios[df_ifood_horarios["periodo"] == periodo_sel_v].groupby(["periodo_semana","horario"])["pedidos"].sum().reset_index()')
nova.append('            if len(df_hor) > 0:')
nova.append('                df_hor_piv = df_hor.pivot(index="horario", columns="periodo_semana", values="pedidos").fillna(0)')
nova.append('                fig_hor = go.Figure(data=go.Heatmap(z=df_hor_piv.values, x=df_hor_piv.columns.tolist(), y=df_hor_piv.index.tolist(), colorscale=[[0,"#F5F0E8"],[0.5,"#B8923A"],[1,VERDE]], texttemplate="%{z:.0f}", textfont=dict(family="Nunito", size=11)))')
nova.append('                fig_hor.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=10), xaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)), yaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)), font=dict(family="Nunito"), height=380, coloraxis_showscale=False)')
nova.append('                st.plotly_chart(fig_hor, use_container_width=True, key="fig_hor_v")')
nova.append('')
nova.append('    # Dias de pico')
nova.append('    with col_h2:')
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Dias de Pico</div>\', unsafe_allow_html=True)')
nova.append('            ordem_dias = ["Segunda","Terca","Quarta","Quinta","Sexta","Sabado","Domingo"]')
nova.append('            df_dias = df_ifood_dias[df_ifood_dias["periodo"] == periodo_sel_v].copy()')
nova.append('            df_dias["dia_norm"] = df_dias["dia_semana"].str.normalize("NFKD").str.encode("ascii","ignore").str.decode("ascii").str.strip()')
nova.append('            df_dias_g = df_dias.groupby("dia_norm")["pedidos"].sum().reset_index()')
nova.append('            df_dias_g = df_dias_g.set_index("dia_norm").reindex([d for d in ordem_dias if d in df_dias_g["dia_norm"].values]).reset_index()')
nova.append('            if len(df_dias_g) > 0:')
nova.append('                fig_dias = go.Figure(go.Bar(x=df_dias_g["dia_norm"], y=df_dias_g["pedidos"], marker_color=VERDE, text=df_dias_g["pedidos"], textposition="outside", textfont=dict(family="Nunito", size=12, color=MARROM)))')
nova.append('                fig_dias.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=10), xaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)), yaxis=dict(showgrid=False, tickfont=dict(family="Nunito", size=11, color=MARROM)), font=dict(family="Nunito"), height=380)')
nova.append('                st.plotly_chart(fig_dias, use_container_width=True, key="fig_dias_v")')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    # Mix de pagamento')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Mix de Pagamento</div>\', unsafe_allow_html=True)')
nova.append('        df_pag = df_ifood_pagamentos[df_ifood_pagamentos["periodo"] == periodo_sel_v].groupby("forma_pagamento")["pedidos"].sum().reset_index().sort_values("pedidos", ascending=False)')
nova.append('        if len(df_pag) > 0:')
nova.append('            fig_pag = go.Figure(go.Pie(labels=df_pag["forma_pagamento"], values=df_pag["pedidos"], hole=0.5, textinfo="label+percent", textfont=dict(family="Nunito", size=12), marker=dict(colors=[VERDE,"#B8923A","#3D7A5C","#7A3D3D","#3D5A7A","#7A5C3D","#5C7A3D","#7A6B3D"])))')
nova.append('            fig_pag.update_layout(paper_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=10), legend=dict(font=dict(family="Nunito", size=11, color=MARROM)), font=dict(family="Nunito"), height=320)')
nova.append('            st.plotly_chart(fig_pag, use_container_width=True, key="fig_pag_v")')
nova.append('')

result = lines[:966] + nova + lines[966:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print(f'Feito! Total: {len(result)} linhas')
