lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')

# Substituir bloco do ranking (linhas 1059-1101)
novo_rank = [
    '        fig_rank = go.Figure()',
    '',
    '        if is_parcial:',
    '            fig_rank.add_trace(go.Bar(',
    '                y=df_rank["filial_curta"],',
    '                x=df_rank["faturamento_projetado"],',
    '                orientation="h",',
    '                name=f"Projetado ({dias_no_mes} dias)",',
    '                marker_color="#B8923A",',
    '                opacity=0.4,',
    '                text=df_rank["proj_fmt"],',
    '                textposition="outside",',
    '                textfont=dict(family="Nunito", size=13, color="#8B6914"),',
    '            ))',
    '',
    '        fig_rank.add_trace(go.Bar(',
    '            y=df_rank["filial_curta"],',
    '            x=df_rank["faturamento"],',
    '            orientation="h",',
    '            name=f"Realizado ({dias_decorridos} dias)" if is_parcial else "Faturamento",',
    '            marker_color=VERDE,',
    '            text=df_rank["fat_fmt"],',
    '            textposition="inside",',
    '            textfont=dict(family="Nunito", size=12, color="white"),',
    '        ))',
    '',
    '        if is_parcial:',
    '            fig_rank.add_annotation(',
    '                text=f"Parcial: {dias_decorridos} de {dias_no_mes} dias | Projecao linear",',
    '                xref="paper", yref="paper", x=0, y=1.12, showarrow=False,',
    '                font=dict(family="Nunito", size=11, color="#B8923A"),',
    '            )',
    '',
    '        fig_rank.update_layout(',
    '            barmode="overlay",',
    '            paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",',
    '            margin=dict(t=40,b=10,l=10,r=200),',
    '            xaxis=dict(showgrid=False, tickfont=dict(family="Nunito", size=11, color=MARROM)),',
    '            yaxis=dict(tickfont=dict(family="Nunito", size=12, color=MARROM)),',
    '            legend=dict(font=dict(family="Nunito", size=11, color=MARROM), orientation="h", yanchor="bottom", y=1.04),',
    '            font=dict(family="Nunito"), height=320',
    '        )',
    '        st.plotly_chart(fig_rank, use_container_width=True, key="fig_rank_v")',
    '',
    '    st.markdown("<br>", unsafe_allow_html=True)',
    '',
    '    # Grafico de evolucao de receita no tempo',
    '    with st.container(border=True):',
    '        st.markdown(\'<div class="section-title">Evolucao de Receita</div>\', unsafe_allow_html=True)',
    '        import calendar',
    '        from datetime import datetime',
    '        evolucao = []',
    '        for p in periodos:',
    '            df_p = df_v[df_v["periodo"] == p]',
    '            fat_p = df_p["faturamento"].sum()',
    '            try:',
    '                partes = p.split("-")',
    '                d_ini = datetime.strptime(partes[0].strip(), "%d/%m/%Y")',
    '                d_fim = datetime.strptime(partes[1].strip(), "%d/%m/%Y")',
    '                dias_dec = (d_fim - d_ini).days + 1',
    '                dias_mes = calendar.monthrange(d_ini.year, d_ini.month)[1]',
    '                mes_map = {"01":"Jan","02":"Fev","03":"Mar","04":"Abr","05":"Mai","06":"Jun","07":"Jul","08":"Ago","09":"Set","10":"Out","11":"Nov","12":"Dez"}',
    '                mes_label = mes_map.get(f"{d_ini.month:02d}", p)',
    '                is_p = dias_dec < dias_mes',
    '                fat_proj = fat_p / dias_dec * dias_mes if is_p else None',
    '                evolucao.append({"mes": mes_label, "fat": fat_p, "proj": fat_proj, "parcial": is_p})',
    '            except:',
    '                evolucao.append({"mes": p[:3], "fat": fat_p, "proj": None, "parcial": False})',
    '',
    '        fig_evo = go.Figure()',
    '        meses = [e["mes"] for e in evolucao]',
    '        fats = [e["fat"] for e in evolucao]',
    '        projs = [e["proj"] for e in evolucao]',
    '        parciais = [e["parcial"] for e in evolucao]',
    '',
    '        # Linha realizado',
    '        fig_evo.add_trace(go.Scatter(',
    '            x=meses, y=fats,',
    '            mode="lines+markers+text",',
    '            name="Realizado",',
    '            line=dict(color=VERDE, width=3),',
    '            marker=dict(size=10, color=VERDE),',
    '            text=[f"R$ {v:,.0f}".replace(",",".") for v in fats],',
    '            textposition="top center",',
    '            textfont=dict(family="Nunito", size=11, color=VERDE),',
    '        ))',
    '',
    '        # Linha projetada para meses parciais',
    '        for i_e, e in enumerate(evolucao):',
    '            if e["parcial"] and e["proj"]:',
    '                fig_evo.add_trace(go.Scatter(',
    '                    x=[meses[i_e], meses[i_e]],',
    '                    y=[fats[i_e], e["proj"]],',
    '                    mode="lines+markers+text",',
    '                    name="Projetado",',
    '                    line=dict(color="#B8923A", width=2, dash="dot"),',
    '                    marker=dict(size=10, color="#B8923A", symbol="diamond"),',
    '                    text=["", f"R$ {e[\'proj\']:,.0f}".replace(",",".")],',
    '                    textposition="top center",',
    '                    textfont=dict(family="Nunito", size=11, color="#B8923A"),',
    '                    showlegend=True,',
    '                ))',
    '',
    '        fig_evo.update_layout(',
    '            paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",',
    '            margin=dict(t=30,b=10,l=10,r=10),',
    '            xaxis=dict(tickfont=dict(family="Nunito", size=12, color=MARROM), showgrid=False),',
    '            yaxis=dict(showgrid=True, gridcolor="#E8DCC8", tickfont=dict(family="Nunito", size=11, color=MARROM)),',
    '            legend=dict(font=dict(family="Nunito", size=11, color=MARROM), orientation="h", yanchor="bottom", y=1.02),',
    '            font=dict(family="Nunito"), height=350,',
    '        )',
    '        st.plotly_chart(fig_evo, use_container_width=True, key="fig_evo_v")',
]

result = lines[:1058] + novo_rank + lines[1102:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print(f'Feito! Total: {len(result)} linhas')
