lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')

for i, line in enumerate(lines):
    if 'OLIVE GARDEN BRAND INTELLIGENCE' in line:
        footer_line = i - 1
        break

nova = []
nova.append('elif aba_sel == "Correlacoes":')
nova.append('    import calendar')
nova.append('    from datetime import datetime')
nova.append('    st.markdown(\'\'\'<div style="font-weight:800; font-size:26px; color:#3D2B1F; letter-spacing:0.08em; text-transform:uppercase; margin-bottom:4px;">Correlacoes & Inteligencia</div>')
nova.append('    <div style="font-size:13px; color:#8B9A2E; letter-spacing:0.1em; margin-bottom:20px;">PADROES, TENDENCIAS, AMEACAS E CAUSALIDADES</div>\'\'\', unsafe_allow_html=True)')
nova.append('')
nova.append('    # Prepara dados base')
nova.append('    df_perf_c = df_perf[df_perf["restaurant"] != "nan"].copy()')
nova.append('    df_perf_c["filial_curta"] = df_perf_c["restaurant"].str.replace("Olive Garden - ", "", regex=False)')
nova.append('    df_perf_c["periodo_curto"] = df_perf_c["periodo"].str.extract(r"(FW\d+ to FW\d+)")')
nova.append('    gss_atual = df_perf_c.sort_values("periodo_curto").groupby("filial_curta").last().reset_index() if len(df_perf_c) > 0 else pd.DataFrame()')
nova.append('    rep_pub = df.groupby("filial").agg(nota_media=("nota", "mean"), pct_pos=("sentimento", lambda x: (x == "Positivo").sum() / len(x) * 100)).reset_index()')
nova.append('    rep_pub["score_externo"] = (((rep_pub["nota_media"] - 1) / 4) * 40 + rep_pub["pct_pos"] * 0.6).clip(0, 100).round(1)')
nova.append('    rep_pub["filial_curta"] = rep_pub["filial"].str.replace("Olive Garden - ", "", regex=False)')
nova.append('    df_v_c = df_ifood_vendas[df_ifood_vendas["logistica"] == "Entrega parceira"].copy()')
nova.append('    df_v_c["filial_curta"] = df_v_c["filial"].str.replace("Olive Garden - ", "", regex=False)')
nova.append('')
nova.append('    # BLOCO 1 — Radar de Saude da Rede')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Radar de Saude da Rede</div>\', unsafe_allow_html=True)')
nova.append('        st.markdown(\'<div style="font-size:12px; color:#8B7A5A; margin-bottom:16px;">Semaforo por filial cruzando GSS interno + Reputacao publica + Sentimento iFood. Identifica quem esta bem, em risco ou em queda.</div>\', unsafe_allow_html=True)')
nova.append('        if len(gss_atual) > 0:')
nova.append('            saude = rep_pub.merge(gss_atual[["filial_curta", "overall_experience", "service", "taste", "speed_of_service"]], on="filial_curta", how="left")')
nova.append('            sent_ifood = df[df["plataforma"] == "iFood"].groupby("filial").agg(pct_pos_if=("sentimento", lambda x: (x=="Positivo").sum()/len(x)*100)).reset_index()')
nova.append('            sent_ifood["filial_curta"] = sent_ifood["filial"].str.replace("Olive Garden - ", "", regex=False)')
nova.append('            saude = saude.merge(sent_ifood[["filial_curta","pct_pos_if"]], on="filial_curta", how="left")')
nova.append('            saude["indice_saude"] = (saude["score_externo"].fillna(70) * 0.4 + saude["overall_experience"].fillna(80) * 0.4 + saude["pct_pos_if"].fillna(70) * 0.2).round(1)')
nova.append('            saude = saude.sort_values("indice_saude", ascending=False)')
nova.append('            cols_radar = st.columns(len(saude))')
nova.append('            for idx, (_, row) in enumerate(saude.iterrows()):')
nova.append('                v = row["indice_saude"]')
nova.append('                cor = "#2e6b3e" if v >= 80 else "#B8923A" if v >= 70 else VERMELHO')
nova.append('                status = "SAUDAVEL" if v >= 80 else "ATENCAO" if v >= 70 else "CRITICO"')
nova.append('                icone = "●" if v >= 80 else "▲" if v >= 70 else "■"')
nova.append('                with cols_radar[idx]:')
nova.append('                    st.markdown(f\'\'\'<div style="background:#3D2B1F; border-radius:10px; padding:16px; text-align:center; border-top:4px solid {cor};">') 
nova.append('                        <div style="font-size:9px; color:#D8CFC0; letter-spacing:2px; margin-bottom:8px;">{row["filial_curta"].upper()}</div>')
nova.append('                        <div style="font-size:28px; color:{cor}; margin-bottom:4px;">{icone}</div>')
nova.append('                        <div style="font-size:11px; font-weight:700; color:{cor}; margin-bottom:12px;">{status}</div>')
nova.append('                        <div style="font-size:10px; color:#D8CFC0; text-align:left;">')
nova.append('                        <div style="margin-bottom:4px;">GSS: <span style="color:#F5F0E8; font-weight:700;">{row["overall_experience"]:.0f}%</span></div>')
nova.append('                        <div style="margin-bottom:4px;">Reputacao: <span style="color:#F5F0E8; font-weight:700;">{row["score_externo"]:.0f}</span></div>')
nova.append('                        <div>iFood: <span style="color:#F5F0E8; font-weight:700;">{row["pct_pos_if"]:.0f}%</span></div>')
nova.append('                        </div></div>\'\'\', unsafe_allow_html=True)')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    # BLOCO 2 — Tendencias e Alertas GSS')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Tendencias GSS — Alertas por Dimensao</div>\', unsafe_allow_html=True)')
nova.append('        st.markdown(\'<div style="font-size:12px; color:#8B7A5A; margin-bottom:16px;">Evolucao de cada dimensao ao longo dos periodos. Dimensoes em queda consistente requerem acao imediata.</div>\', unsafe_allow_html=True)')
nova.append('        if len(df_perf_c["periodo_curto"].dropna().unique()) > 1:')
nova.append('            metricas_t = {"overall_experience": "Exp. Geral", "value": "Valor", "service": "Atendimento", "taste": "Sabor", "speed_of_service": "Velocidade", "clean": "Limpeza", "soup_salad_refill": "Refil Sopa", "breadstick_refill": "Refil Bread"}')
nova.append('            trend_df = df_perf_c.groupby("periodo_curto")[list(metricas_t.keys())].mean().reset_index().sort_values("periodo_curto")')
nova.append('            alertas = []')
nova.append('            for col, lbl in metricas_t.items():')
nova.append('                if len(trend_df) >= 2:')
nova.append('                    delta = trend_df[col].iloc[-1] - trend_df[col].iloc[0]')
nova.append('                    delta_recente = trend_df[col].iloc[-1] - trend_df[col].iloc[-2]')
nova.append('                    if delta < -2 or delta_recente < -1.5:')
nova.append('                        alertas.append({"dim": lbl, "delta": delta, "delta_rec": delta_recente, "tipo": "ALERTA"})')
nova.append('                    elif delta > 2:')
nova.append('                        alertas.append({"dim": lbl, "delta": delta, "delta_rec": delta_recente, "tipo": "POSITIVO"})')
nova.append('                    else:')
nova.append('                        alertas.append({"dim": lbl, "delta": delta, "delta_rec": delta_recente, "tipo": "ESTAVEL"})')
nova.append('            col_a1, col_a2 = st.columns([1, 2])')
nova.append('            with col_a1:')
nova.append('                for a in sorted(alertas, key=lambda x: x["delta"]):')
nova.append('                    cor_a = VERMELHO if a["tipo"] == "ALERTA" else "#2e6b3e" if a["tipo"] == "POSITIVO" else "#B8923A"')
nova.append('                    icone_a = "▼" if a["tipo"] == "ALERTA" else "▲" if a["tipo"] == "POSITIVO" else "—"')
nova.append('                    st.markdown(f\'<div style="padding:8px 0; border-bottom:1px solid #e8ddc8; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:12px; color:#3D2B1F; font-weight:600;">{a["dim"]}</span><span style="font-size:12px; color:{cor_a}; font-weight:700;">{icone_a} {a["delta"]:+.1f}%</span></div>\', unsafe_allow_html=True)')
nova.append('            with col_a2:')
nova.append('                fig_trend = go.Figure()')
nova.append('                for col, lbl in metricas_t.items():')
nova.append('                    delta = trend_df[col].iloc[-1] - trend_df[col].iloc[0] if len(trend_df) > 1 else 0')
nova.append('                    cor_line = VERMELHO if delta < -2 else "#2e6b3e" if delta > 2 else "#B8923A"')
nova.append('                    fig_trend.add_trace(go.Scatter(x=trend_df["periodo_curto"], y=trend_df[col].round(1), mode="lines+markers", name=f"{lbl} ({delta:+.1f}%)", line=dict(color=cor_line, width=2), marker=dict(size=6)))')
nova.append('                fig_trend.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=10), xaxis=dict(tickfont=dict(family="Nunito", size=10, color=MARROM)), yaxis=dict(range=[60,105], showgrid=True, gridcolor="#E8DCC8", tickfont=dict(family="Nunito", size=10, color=MARROM)), legend=dict(font=dict(family="Nunito", size=9, color=MARROM), orientation="h", yanchor="bottom", y=1.02), font=dict(family="Nunito"), height=320)')
nova.append('                st.plotly_chart(fig_trend, use_container_width=True, key="fig_trend_c")')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    # BLOCO 3 — Padroes de Causalidade')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Padroes de Causalidade</div>\', unsafe_allow_html=True)')
nova.append('        st.markdown(\'<div style="font-size:12px; color:#8B7A5A; margin-bottom:16px;">Correlacoes entre dimensoes internas e percepcao publica. Identifica o que mais impacta a reputacao.</div>\', unsafe_allow_html=True)')
nova.append('        if len(gss_atual) > 0 and len(rep_pub) > 0:')
nova.append('            caus_df = rep_pub.merge(gss_atual[["filial_curta","overall_experience","service","taste","speed_of_service","value"]], on="filial_curta", how="left").dropna()')
nova.append('            col_c1, col_c2, col_c3 = st.columns(3)')
nova.append('            dims = [("service","Atendimento vs Reputacao","Atendimento GSS"),("taste","Sabor vs Reputacao","Sabor GSS"),("speed_of_service","Velocidade vs Reputacao","Velocidade GSS")]')
nova.append('            for col_c, (dim, titulo, xlabel) in zip([col_c1,col_c2,col_c3], dims):')
nova.append('                with col_c:')
nova.append('                    fig_c = go.Figure(go.Scatter(x=caus_df[dim], y=caus_df["score_externo"], mode="markers+text", text=caus_df["filial_curta"], textposition="top center", textfont=dict(family="Nunito", size=9, color=MARROM), marker=dict(size=12, color=VERDE, opacity=0.8)))')
nova.append('                    fig_c.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=30,b=10,l=10,r=10), title=dict(text=titulo, font=dict(family="Nunito", size=11, color=MARROM), x=0.5), xaxis=dict(title=xlabel, tickfont=dict(family="Nunito", size=9, color=MARROM), gridcolor="#E8DCC8"), yaxis=dict(title="Reputacao Publica", tickfont=dict(family="Nunito", size=9, color=MARROM), gridcolor="#E8DCC8"), font=dict(family="Nunito"), height=280)')
nova.append('                    st.plotly_chart(fig_c, use_container_width=True, key=f"fig_caus_{dim}")')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    # BLOCO 4 — Sazonalidade iFood')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Sazonalidade iFood</div>\', unsafe_allow_html=True)')
nova.append('        st.markdown(\'<div style="font-size:12px; color:#8B7A5A; margin-bottom:16px;">Padroes de demanda por dia da semana e horario. Identifica concentracao operacional e oportunidades.</div>\', unsafe_allow_html=True)')
nova.append('        col_s1, col_s2 = st.columns(2)')
nova.append('        with col_s1:')
nova.append('            ordem_dias = ["Segunda","Terca","Quarta","Quinta","Sexta","Sabado","Domingo"]')
nova.append('            df_dias_c = df_ifood_dias.copy()')
nova.append('            df_dias_c["dia_norm"] = df_dias_c["dia_semana"].str.normalize("NFKD").str.encode("ascii","ignore").str.decode("ascii").str.strip()')
nova.append('            df_dias_agg = df_dias_c.groupby("dia_norm")["pedidos"].sum().reset_index()')
nova.append('            df_dias_agg = df_dias_agg.set_index("dia_norm").reindex([d for d in ordem_dias if d in df_dias_agg["dia_norm"].values]).reset_index()')
nova.append('            fig_dias_c = go.Figure(go.Bar(x=df_dias_agg["dia_norm"], y=df_dias_agg["pedidos"], marker_color=[VERDE if v == df_dias_agg["pedidos"].max() else "#B8923A" if v >= df_dias_agg["pedidos"].quantile(0.7) else "#D8CFC0" for v in df_dias_agg["pedidos"]], text=df_dias_agg["pedidos"], textposition="outside", textfont=dict(family="Nunito", size=11, color=MARROM)))')
nova.append('            fig_dias_c.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=30,b=10,l=10,r=10), title=dict(text="Pedidos por Dia da Semana (acumulado)", font=dict(family="Nunito", size=11, color=MARROM), x=0.5), xaxis=dict(tickfont=dict(family="Nunito", size=10, color=MARROM)), yaxis=dict(showgrid=False), font=dict(family="Nunito"), height=280)')
nova.append('            st.plotly_chart(fig_dias_c, use_container_width=True, key="fig_dias_c")')
nova.append('        with col_s2:')
nova.append('            df_hor_c = df_ifood_horarios.groupby(["periodo_semana","horario"])["pedidos"].sum().reset_index()')
nova.append('            if len(df_hor_c) > 0:')
nova.append('                df_hor_piv_c = df_hor_c.pivot(index="horario", columns="periodo_semana", values="pedidos").fillna(0)')
nova.append('                fig_hor_c = go.Figure(data=go.Heatmap(z=df_hor_piv_c.values, x=df_hor_piv_c.columns.tolist(), y=df_hor_piv_c.index.tolist(), colorscale=[[0,"#F5F0E8"],[0.5,"#B8923A"],[1,VERDE]], texttemplate="%{z:.0f}", textfont=dict(family="Nunito", size=10)))')
nova.append('                fig_hor_c.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=30,b=10,l=10,r=10), title=dict(text="Horario de Pico Acumulado", font=dict(family="Nunito", size=11, color=MARROM), x=0.5), xaxis=dict(tickfont=dict(family="Nunito", size=10, color=MARROM)), yaxis=dict(tickfont=dict(family="Nunito", size=10, color=MARROM)), font=dict(family="Nunito"), height=280, coloraxis_showscale=False)')
nova.append('                st.plotly_chart(fig_hor_c, use_container_width=True, key="fig_hor_c")')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    # BLOCO 5 — Divergencias Internas vs Externas')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Divergencias — Percepcao Interna vs Externa</div>\', unsafe_allow_html=True)')
nova.append('        st.markdown(\'<div style="font-size:12px; color:#8B7A5A; margin-bottom:16px;">Onde a experiencia interna e a reputacao publica divergem. Sinal de alerta estrategico — o cliente esta saindo diferente do que a pesquisa indica.</div>\', unsafe_allow_html=True)')
nova.append('        if len(gss_atual) > 0 and len(rep_pub) > 0:')
nova.append('            div_df = rep_pub.merge(gss_atual[["filial_curta","overall_experience"]], on="filial_curta", how="left").dropna()')
nova.append('            div_df["divergencia"] = (div_df["overall_experience"] - div_df["score_externo"]).round(1)')
nova.append('            div_df = div_df.sort_values("divergencia", ascending=False)')
nova.append('            for _, row in div_df.iterrows():')
nova.append('                div = row["divergencia"]')
nova.append('                if div > 10:')
nova.append('                    cor = "#2e6b3e"; icone = "▲ Interno ACIMA do publico"; msg = "Oportunidade: amplificar reputacao publica"')
nova.append('                elif div < -10:')
nova.append('                    cor = VERMELHO; icone = "▼ Publico ACIMA do interno"; msg = "Alerta: cliente insatisfeito nao aparece na pesquisa?"')
nova.append('                else:')
nova.append('                    cor = "#B8923A"; icone = "— Alinhado"; msg = "Percepcao interna e externa consistentes"')
nova.append('                st.markdown(f\'<div style="padding:10px 0; border-bottom:1px solid #e8ddc8;"><div style="display:flex; justify-content:space-between; align-items:center;"><span style="font-size:13px; font-weight:700; color:#3D2B1F;">{row["filial_curta"]}</span><span style="font-size:12px; color:{cor}; font-weight:700;">{div:+.1f} pts — {icone}</span></div><div style="font-size:11px; color:#8B7A5A; margin-top:3px;">GSS: {row["overall_experience"]:.1f}% | Reputacao: {row["score_externo"]:.1f} | {msg}</div></div>\', unsafe_allow_html=True)')
nova.append('')

result = lines[:1401] + nova + lines[footer_line-1:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print(f'Feito! Total: {len(result)} linhas')
