lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')
nova = []
nova.append('elif aba_sel == "OlivIA":')
nova.append('    st.markdown(')
nova.append('        """<div style="background:#3D2B1F; border-radius:16px; padding:60px; margin-bottom:24px; text-align:center;">')
nova.append('        <div style="font-size:11px; letter-spacing:5px; color:#8B9A2E; text-transform:uppercase; margin-bottom:24px; font-family:Arial,sans-serif;">Agente de inteligencia · Olive Garden Brasil</div>')
nova.append('        <div style="font-family:Georgia,serif; font-size:80px; font-weight:800; line-height:1; letter-spacing:3px; margin-bottom:0; display:inline-block;">')
nova.append('        <span style="color:#F5F0E8; font-family:Georgia,serif; font-size:80px; font-weight:800;">Oliv</span><span style="color:#8B9A2E; font-family:Georgia,serif; font-size:80px; font-weight:800;">IA</span>')
nova.append('        </div>')
nova.append('        <div style="width:64px; height:2px; background:#8B9A2E; margin:24px auto;"></div>')
nova.append('        <div style="font-size:14px; color:#D8CFC0; line-height:1.8; max-width:520px; font-family:Arial,sans-serif; margin:0 auto;">Analiso reviews, redes sociais, pesquisa interna e noticias do mercado para gerar insights estrategicos em tempo real.</div>')
nova.append('        </div>""",')
nova.append('        unsafe_allow_html=True')
nova.append('    )')
nova.append('    st.markdown(')
nova.append('        """<div style="background:white; border-radius:12px; border:1px solid #E8DCC8; padding:24px 28px; margin-bottom:24px; display:flex; align-items:center; gap:24px;">')
nova.append('        <div style="width:48px; height:48px; border-radius:50%; background:#4D3321; display:flex; align-items:center; justify-content:center; flex-shrink:0;">')
nova.append('        <svg width=\'20\' height=\'20\' viewBox=\'0 0 24 24\' fill=\'none\'><circle cx=\'12\' cy=\'12\' r=\'10\' stroke=\'#8B9A2E\' stroke-width=\'1.5\'/><path d=\'M8 12h8M12 8v8\' stroke=\'#8B9A2E\' stroke-width=\'1.5\' stroke-linecap=\'round\'/></svg>')
nova.append('        </div>')
nova.append('        <div style="flex:1;">')
nova.append('        <div style="font-size:11px; color:#8B9A2E; letter-spacing:2px; text-transform:uppercase; margin-bottom:4px;">Pronto para analisar</div>')
nova.append('        <div style="font-size:13px; color:#5C3D1E; line-height:1.5;">Clique em <strong style=\'color:#4D3321;\'>Gerar Briefing Executivo</strong> para uma analise completa, ou faca uma pergunta no chat abaixo.</div>')
nova.append('        </div></div>""",')
nova.append('        unsafe_allow_html=True')
nova.append('    )')
result = lines[:859] + nova + lines[882:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print('Feito! Linhas:', len(result))
