lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')
nova = []
nova.append('elif aba_sel == "OlivIA":')
nova.append('    st.markdown(')
nova.append('        """<div style="background:#3D2B1F; border-radius:16px; padding:52px 60px; margin-bottom:24px;">')
nova.append('        <div style="font-size:11px; letter-spacing:5px; color:#8B9A2E; text-transform:uppercase; margin-bottom:20px; font-family:Arial,sans-serif;">Agente de inteligencia · Olive Garden Brasil</div>')
nova.append('        <div style="font-family:Georgia,serif; font-size:72px; font-weight:800; line-height:1; letter-spacing:2px; margin-bottom:0;">')
nova.append('        <span style="color:#F5F0E8; font-family:Georgia,serif; font-size:72px; font-weight:800;">Oliv</span><span style="color:#8B9A2E; font-family:Georgia,serif; font-size:72px; font-weight:800;">IA</span>')
nova.append('        </div>')
nova.append('        <div style="width:64px; height:2px; background:#8B9A2E; margin-top:20px; margin-bottom:20px;"></div>')
nova.append('        <div style="font-size:14px; color:#D8CFC0; line-height:1.8; max-width:520px; font-family:Arial,sans-serif;">Analiso reviews, redes sociais, pesquisa interna e noticias do mercado para gerar insights estrategicos em tempo real.</div>')
nova.append('        </div>""",')
nova.append('        unsafe_allow_html=True')
nova.append('    )')
result = lines[:859] + nova + lines[871:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print('Feito! Linhas:', len(result))
