lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')

for i, line in enumerate(lines):
    if 'OLIVE GARDEN BRAND INTELLIGENCE' in line:
        footer_line = i - 1
        break

nova = []
nova.append('elif aba_sel == "Correlacoes":')
nova.append('    st.markdown(')
nova.append('        \'\'\'<div style="font-weight:800; font-size:26px; color:#3D2B1F; letter-spacing:0.08em; text-transform:uppercase; margin-bottom:4px;">Correlacoes & Tendencias</div>')
nova.append('        <div style="font-size:13px; color:#8B9A2E; letter-spacing:0.1em; margin-bottom:20px;">LEITURAS RAPIDAS E DIRETAS</div>\'\'\',')
nova.append('        unsafe_allow_html=True')
nova.append('    )')
nova.append('')
nova.append('    # Prepara dados base')
nova.append('    df_perf_c = df_perf[df_perf["restaurant"] != "nan"].copy()')
nova.append('    df_perf_c["filial_curta"] = df_perf_c["restaurant"].str.replace("Olive Garden - ", "")')
nova.append('    df_perf_c["periodo_curto"] = df_perf_c["periodo"].str.extract(r"(FW\d+ to FW\d+)")')
nova.append('    gss_atual = df_perf_c.sort_values("periodo_curto").groupby("filial_curta").last().reset_index() if len(df_perf_c) > 0 else pd.DataFrame()')
nova.append('    rep_pub = df.groupby("filial").agg(nota_media=("nota", "mean"), pct_pos=("sentimento", lambda x: (x == "Positivo").sum() / len(x) * 100)).reset_index()')
nova.append('    rep_pub["score_externo"] = (((rep_pub["nota_media"] - 1) / 4) * 40 + rep_pub["pct_pos"] * 0.6).clip(0, 100).round(1)')
nova.append('    rep_pub["filial_curta"] = rep_pub["filial"].str.replace("Olive Garden - ", "")')
nova.append('')
nova.append('    # 1. Ranking de Saude por Filial')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Ranking de Saude por Filial</div>\', unsafe_allow_html=True)')
nova.append('        st.markdown(\'<div style="font-size:12px; color:#8B7A5A; margin-bottom:16px;">Indice combinado de GSS interno + Reputacao publica. Identifica qual filial precisa de atencao agora.</div>\', unsafe_allow_html=True)')
nova.append('        if len(gss_atual) > 0:')
nova.append('            saude = rep_pub.merge(gss_atual[["filial_curta", "overall_experience"]], on="filial_curta", how="left")')
nova.append('            saude["indice_saude"] = (saude["score_externo"] * 0.5 + saude["overall_experience"].fillna(80) * 0.5).round(1)')
nova.append('            saude = saude.sort_values("indice_saude", ascending=False)')
nova.append('            for _, row in saude.iterrows():')
nova.append('                v = row["indice_saude"]')
nova.append('                cor = VERDE if v >= 80 else "#B8923A" if v >= 70 else VERMELHO')
nova.append('                status = "SAUDAVEL" if v >= 80 else "ATENCAO" if v >= 70 else "CRITICO"')
nova.append('                pct = int((v / 100) * 100)')
nova.append('                st.markdown(f\'\'\'<div style="margin-bottom:14px;">')
nova.append('                    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:6px;">')
nova.append('                    <span style="font-size:13px; font-weight:700; color:#3D2B1F;">{row["filial_curta"]}</span>')
nova.append('                    <div style="display:flex; align-items:center; gap:12px;">')
nova.append('                    <span style="font-size:11px; font-weight:700; color:{cor}; background:rgba(0,0,0,0.05); padding:2px 10px; border-radius:20px;">{status}</span>')
nova.append('                    <span style="font-size:13px; font-weight:700; color:{cor};">{v:.1f}</span>')
nova.append('                    </div></div>')
nova.append('                    <div style="background:#e8ddc8; border-radius:4px; height:8px;">')
nova.append('                    <div style="background:{cor}; width:{pct}%; height:8px; border-radius:4px;"></div>')
nova.append('                    </div></div>\'\'\', unsafe_allow_html=True)')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    # 2. Divergencias GSS vs Reputacao')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Divergencias — Percepcao Interna vs Externa</div>\', unsafe_allow_html=True)')
nova.append('        st.markdown(\'<div style="font-size:12px; color:#8B7A5A; margin-bottom:16px;">Onde o cliente esta saindo diferente do que a pesquisa interna indica. Divergencia alta = risco de reputacao.</div>\', unsafe_allow_html=True)')
nova.append('        if len(gss_atual) > 0:')
nova.append('            div_df = rep_pub.merge(gss_atual[["filial_curta", "overall_experience"]], on="filial_curta", how="left").dropna()')
nova.append('            div_df["divergencia"] = (div_df["overall_experience"] - div_df["score_externo"]).round(1)')
nova.append('            div_df = div_df.sort_values("divergencia", ascending=False)')
nova.append('            for _, row in div_df.iterrows():')
nova.append('                div = row["divergencia"]')
nova.append('                if div > 10:')
nova.append('                    cor = "#2e6b3e"; icone = "Interno ACIMA do publico"; msg = "Oportunidade de amplificar reputacao"')
nova.append('                elif div < -10:')
nova.append('                    cor = VERMELHO; icone = "Publico ACIMA do interno"; msg = "Atencao — cliente insatisfeito nao aparece na pesquisa?"')
nova.append('                else:')
nova.append('                    cor = "#B8923A"; icone = "Alinhado"; msg = "Percepcao interna e externa consistentes"')
nova.append('                st.markdown(f\'<div style="padding:10px 0; border-bottom:1px solid #e8ddc8;">')
nova.append('                    <div style="display:flex; justify-content:space-between; align-items:center;">')
nova.append('                    <span style="font-size:13px; font-weight:700; color:#3D2B1F;">{row["filial_curta"]}</span>')
nova.append('                    <span style="font-size:12px; color:{cor}; font-weight:700;">{div:+.1f} pts — {icone}</span>')
nova.append('                    </div>')
nova.append('                    <div style="font-size:11px; color:#8B7A5A; margin-top:3px;">GSS: {row["overall_experience"]:.1f}% | Reputacao: {row["score_externo"]:.1f} | {msg}</div>')
nova.append('                    </div>\', unsafe_allow_html=True)')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    # 3. Evolucao do Sentimento Publico')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Sentimento Publico por Plataforma</div>\', unsafe_allow_html=True)')
nova.append('        st.markdown(\'<div style="font-size:12px; color:#8B7A5A; margin-bottom:16px;">Distribuicao do sentimento em cada plataforma. Identifica onde a percepcao e mais critica.</div>\', unsafe_allow_html=True)')
nova.append('        sent_plat = df.groupby(["plataforma", "sentimento"]).size().reset_index(name="total")')
nova.append('        sent_pct = sent_plat.copy()')
nova.append('        sent_pct["pct"] = sent_pct.groupby("plataforma")["total"].transform(lambda x: x / x.sum() * 100).round(1)')
nova.append('        fig_sent = go.Figure()')
nova.append('        cores_sent = {"Positivo": VERDE, "Neutro": "#B8923A", "Negativo": VERMELHO}')
nova.append('        for sent in ["Positivo", "Neutro", "Negativo"]:')
nova.append('            df_s = sent_pct[sent_pct["sentimento"] == sent]')
nova.append('            fig_sent.add_trace(go.Bar(')
nova.append('                name=sent,')
nova.append('                x=df_s["plataforma"],')
nova.append('                y=df_s["pct"],')
nova.append('                marker_color=cores_sent[sent],')
nova.append('                text=df_s["pct"].apply(lambda x: f"{x:.0f}%"),')
nova.append('                textposition="inside",')
nova.append('                textfont=dict(family="Nunito", size=12, color="white"),')
nova.append('            ))')
nova.append('        fig_sent.update_layout(')
nova.append('            barmode="stack",')
nova.append('            paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",')
nova.append('            margin=dict(t=10, b=10, l=10, r=10),')
nova.append('            legend=dict(font=dict(family="Nunito", size=11, color=MARROM), orientation="h", yanchor="bottom", y=1.02),')
nova.append('            xaxis=dict(tickfont=dict(family="Nunito", size=12, color=MARROM)),')
nova.append('            yaxis=dict(title="% do total", showgrid=False, tickfont=dict(family="Nunito", size=11, color=MARROM)),')
nova.append('            font=dict(family="Nunito"),')
nova.append('            height=320,')
nova.append('        )')
nova.append('        st.plotly_chart(fig_sent, use_container_width=True, key="fig_sent_plat")')
nova.append('')

result = lines[:1127] + nova + lines[footer_line-1:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print('Feito! Linhas:', len(result))
