lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')

nova_secao = [
    '',
    '    # Qualidade iFood por Tags',
    '    if len(df_ifood_tags) > 0:',
    '        st.markdown("<br>", unsafe_allow_html=True)',
    '        with st.container(border=True):',
    '            st.markdown(\'<div class="section-title">Qualidade iFood — Analise por Tags</div>\', unsafe_allow_html=True)',
    '            st.markdown(\'<div style="font-size:12px; color:#8B7A5A; margin-bottom:16px;">Percentual de clientes que avaliaram positivamente cada atributo. Baseado nas tags do relatorio oficial iFood.</div>\', unsafe_allow_html=True)',
    '            periodos_tags = sorted(df_ifood_tags["periodo"].unique())',
    '            periodo_tag_sel = st.selectbox("Periodo:", periodos_tags, index=len(periodos_tags)-1, key="periodo_tags")',
    '            df_tags_f = df_ifood_tags[df_ifood_tags["periodo"] == periodo_tag_sel]',
    '',
    '            col_tp, col_tn = st.columns(2)',
    '',
    '            with col_tp:',
    '                st.markdown(\'<div style="font-size:11px; font-weight:700; color:#2e6b3e; margin-bottom:8px;">ATRIBUTOS POSITIVOS</div>\', unsafe_allow_html=True)',
    '                df_pos = df_tags_f[df_tags_f["tipo"] == "positiva"].groupby("tag")["pct_sim"].mean().reset_index().sort_values("pct_sim", ascending=True)',
    '                if len(df_pos) > 0:',
    '                    fig_tp = go.Figure(go.Bar(',
    '                        y=df_pos["tag"], x=df_pos["pct_sim"],',
    '                        orientation="h",',
    '                        marker_color=[VERDE if v >= 50 else "#B8923A" for v in df_pos["pct_sim"]],',
    '                        text=df_pos["pct_sim"].apply(lambda v: f"{v:.0f}%"),',
    '                        textposition="outside",',
    '                        textfont=dict(family="Nunito", size=11, color=MARROM),',
    '                    ))',
    '                    fig_tp.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=10,b=10,l=10,r=60), xaxis=dict(range=[0,110], showgrid=False, tickfont=dict(family="Nunito", size=10, color=MARROM)), yaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)), font=dict(family="Nunito"), height=300)',
    '                    st.plotly_chart(fig_tp, use_container_width=True, key="fig_tags_pos")',
    '',
    '            with col_tn:',
    '                st.markdown(\'<div style="font-size:11px; font-weight:700; color:#8B2E2E; margin-bottom:8px;">PROBLEMAS REPORTADOS</div>\', unsafe_allow_html=True)',
    '                df_neg = df_tags_f[df_tags_f["tipo"] == "negativa"].groupby("tag")["pct_sim"].mean().reset_index().sort_values("pct_sim", ascending=False)',
    '                if len(df_neg) > 0 and df_neg["pct_sim"].sum() > 0:',
    '                    fig_tn = go.Figure(go.Bar(',
    '                        x=df_neg["tag"], y=df_neg["pct_sim"],',
    '                        marker_color=[VERMELHO if v > 5 else "#B8923A" if v > 0 else "#E8DCC8" for v in df_neg["pct_sim"]],',
    '                        text=df_neg["pct_sim"].apply(lambda v: f"{v:.0f}%"),',
    '                        textposition="outside",',
    '                        textfont=dict(family="Nunito", size=11, color=MARROM),',
    '                    ))',
    '                    fig_tn.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", margin=dict(t=20,b=10,l=10,r=10), xaxis=dict(tickfont=dict(family="Nunito", size=10, color=MARROM)), yaxis=dict(range=[0,30], showgrid=False), font=dict(family="Nunito"), height=300)',
    '                    st.plotly_chart(fig_tn, use_container_width=True, key="fig_tags_neg")',
    '                else:',
    '                    st.markdown(\'<div style="padding:40px; text-align:center; color:#2e6b3e; font-size:13px; font-weight:700;">Nenhum problema reportado neste periodo!</div>\', unsafe_allow_html=True)',
    '',
    '            # Score de qualidade por filial',
    '            st.markdown("<br>", unsafe_allow_html=True)',
    '            st.markdown(\'<div style="font-size:12px; font-weight:700; color:#3D2B1F; margin-bottom:12px;">Score de Qualidade por Filial</div>\', unsafe_allow_html=True)',
    '            score_filial = df_tags_f[df_tags_f["tipo"] == "positiva"].groupby("filial")["pct_sim"].mean().reset_index()',
    '            score_filial.columns = ["filial", "score"]',
    '            score_filial["filial_curta"] = score_filial["filial"].str.replace("Olive Garden - ", "", regex=False)',
    '            score_filial = score_filial.sort_values("score", ascending=False)',
    '            for _, row in score_filial.iterrows():',
    '                v = row["score"]',
    '                cor = "#2e6b3e" if v >= 50 else "#B8923A" if v >= 30 else VERMELHO',
    '                pct = int(v)',
    '                st.markdown(f\'\'\'<div style="margin-bottom:10px;">',
    '                    <div style="display:flex; justify-content:space-between; margin-bottom:4px;">',
    '                    <span style="font-size:12px; font-weight:700; color:#3D2B1F;">{row["filial_curta"]}</span>',
    '                    <span style="font-size:12px; font-weight:700; color:{cor};">{v:.0f}%</span>',
    '                    </div>',
    '                    <div style="background:#e8ddc8; border-radius:4px; height:6px;">',
    '                    <div style="background:{cor}; width:{pct}%; height:6px; border-radius:4px;"></div>',
    '                    </div></div>\'\'\', unsafe_allow_html=True)',
]

# Inserir antes do elif aba_sel == "Social" na linha 524
for i, line in enumerate(lines):
    if line.strip() == 'elif aba_sel == "Social":' and i > 500:
        insert_at = i
        break

result = lines[:insert_at] + nova_secao + lines[insert_at:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print(f'Feito! Total: {len(result)} linhas')
