lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')
for i, line in enumerate(lines):
    if 'OLIVE GARDEN BRAND INTELLIGENCE' in line:
        footer_line = i - 1
        break
for i, line in enumerate(lines):
    if 'elif aba_sel == "OlivIA":' in line:
        olivia_line = i
        break

nova = []
nova.append('elif aba_sel == "fix_ifood_calls.py$":')
nova.append('    st.markdown(')
nova.append('        \'\'\'<div style="font-weight:800; font-size:26px; color:#3D2B1F; letter-spacing:0.08em; text-transform:uppercase; margin-bottom:4px;">fix_ifood_calls.py$</div>')
nova.append('        <div style="font-size:13px; color:#8B9A2E; letter-spacing:0.1em; margin-bottom:20px;">PERFORMANCE FINANCEIRA — iFOOD</div>\'\'\',')
nova.append('        unsafe_allow_html=True')
nova.append('    )')
nova.append('')
nova.append('    # Prepara dados')
nova.append('    df_v = df_ifood_vendas[df_ifood_vendas["logistica"] == "Entrega parceira"].copy()')
nova.append('    df_v["filial_curta"] = df_v["filial"].str.replace("Olive Garden - ", "")')
nova.append('    periodos = sorted(df_v["periodo"].unique())')
nova.append('')
nova.append('    # Bloco 1 — Cards executivos por periodo')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Visao Executiva — Comparativo Mensal</div>\', unsafe_allow_html=True)')
nova.append('        cols_p = st.columns(len(periodos))')
nova.append('        for idx, periodo in enumerate(periodos):')
nova.append('            df_per = df_v[df_v["periodo"] == periodo]')
nova.append('            fat = df_per["faturamento"].sum()')
nova.append('            ped = df_per["pedidos"].sum()')
nova.append('            tkt = df_per["faturamento"].sum() / df_per["pedidos"].sum() if df_per["pedidos"].sum() > 0 else 0')
nova.append('            nov = df_per["novos_clientes"].sum()')
nova.append('            with cols_p[idx]:')
nova.append('                st.markdown(f\'\'\'<div style="background:#3D2B1F; border-radius:12px; padding:20px; color:#F5F0E8;">')
nova.append('                    <div style="font-size:10px; letter-spacing:3px; color:#8B9A2E; text-transform:uppercase; margin-bottom:12px;">{periodo}</div>')
nova.append('                    <div style="display:grid; grid-template-columns:1fr 1fr; gap:12px;">')
nova.append('                    <div><div style="font-size:10px; color:#D8CFC0;">Faturamento</div><div style="font-size:20px; font-weight:700; color:#F5F0E8;">R</div></div>')
nova.append('                    <div><div style="font-size:10px; color:#D8CFC0;">Pedidos</div><div style="font-size:20px; font-weight:700; color:#F5F0E8;">{ped:,}</div></div>')
nova.append('                    <div><div style="font-size:10px; color:#D8CFC0;">Ticket Medio</div><div style="font-size:20px; font-weight:700; color:#8B9A2E;">R</div></div>')
nova.append('                    <div><div style="font-size:10px; color:#D8CFC0;">Novos Clientes</div><div style="font-size:20px; font-weight:700; color:#8B9A2E;">{nov:,}</div></div>')
nova.append('                    </div></div>\'\'\', unsafe_allow_html=True)')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    # Bloco 2 — Ranking por filial')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Faturamento por Filial</div>\', unsafe_allow_html=True)')
nova.append('        periodo_sel_v = st.selectbox("Periodo:", periodos, key="periodo_v", index=len(periodos)-1)')
nova.append('        df_rank = df_v[df_v["periodo"] == periodo_sel_v].groupby("filial_curta").agg(faturamento=("faturamento","sum"), pedidos=("pedidos","sum"), ticket_medio=("ticket_medio","mean"), novos_clientes=("novos_clientes","sum")).reset_index().sort_values("faturamento", ascending=True)')
nova.append('        fig_rank = go.Figure()')
nova.append('        fig_rank.add_trace(go.Bar(')
nova.append('            y=df_rank["filial_curta"],')
nova.append('            x=df_rank["faturamento"],')
nova.append('            orientation="h",')
nova.append('            marker_color=VERDE,')
nova.append('            text=df_rank["faturamento"].apply(lambda x: f"R"),')
nova.append('            textposition="outside",')
nova.append('            textfont=dict(family="Nunito", size=12),')
nova.append('        ))')
nova.append('        fig_rank.update_layout(')
nova.append('            paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",')
nova.append('            margin=dict(t=10, b=10, l=10, r=10),')
nova.append('            xaxis=dict(showgrid=False, tickfont=dict(family="Nunito", size=11, color=MARROM)),')
nova.append('            yaxis=dict(tickfont=dict(family="Nunito", size=12, color=MARROM)),')
nova.append('            font=dict(family="Nunito"), height=300,')
nova.append('        )')
nova.append('        st.plotly_chart(fig_rank, use_container_width=True, key="fig_rank_v")')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    col_h1, col_h2 = st.columns(2)')
nova.append('')
nova.append('    # Bloco 3 — Horario de pico')
nova.append('    with col_h1:')
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Horario de Pico</div>\', unsafe_allow_html=True)')
nova.append('            df_hor = df_ifood_horarios[df_ifood_horarios["periodo"] == periodo_sel_v].groupby(["periodo_semana","horario"])["pedidos"].sum().reset_index()')
nova.append('            df_hor_piv = df_hor.pivot(index="horario", columns="periodo_semana", values="pedidos").fillna(0)')
nova.append('            fig_hor = go.Figure(data=go.Heatmap(')
nova.append('                z=df_hor_piv.values,')
nova.append('                x=df_hor_piv.columns.tolist(),')
nova.append('                y=df_hor_piv.index.tolist(),')
nova.append('                colorscale=[[0,"#F5F0E8"],[0.5,"#B8923A"],[1,VERDE]],')
nova.append('                texttemplate="%{z}",')
nova.append('                textfont=dict(family="Nunito", size=11),')
nova.append('            ))')
nova.append('            fig_hor.update_layout(')
nova.append('                paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",')
nova.append('                margin=dict(t=10, b=10, l=10, r=10),')
nova.append('                xaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)),')
nova.append('                yaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)),')
nova.append('                font=dict(family="Nunito"), height=350, coloraxis_showscale=False,')
nova.append('            )')
nova.append('            st.plotly_chart(fig_hor, use_container_width=True, key="fig_hor")')
nova.append('')
nova.append('    # Bloco 4 — Dias de pico')
nova.append('    with col_h2:')
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Dias de Pico</div>\', unsafe_allow_html=True)')
nova.append('            ordem_dias = ["Segunda","Terca","Quarta","Quinta","Sexta","Sabado","Domingo"]')
nova.append('            df_dias = df_ifood_dias[df_ifood_dias["periodo"] == periodo_sel_v].copy()')
nova.append('            df_dias["dia_semana"] = df_dias["dia_semana"].str.normalize("NFKD").str.encode("ascii","ignore").str.decode("ascii")')
nova.append('            df_dias_g = df_dias.groupby("dia_semana")["pedidos"].sum().reindex([d for d in ordem_dias if d in df_dias["dia_semana"].values]).reset_index()')
nova.append('            fig_dias = go.Figure(go.Bar(')
nova.append('                x=df_dias_g["dia_semana"],')
nova.append('                y=df_dias_g["pedidos"],')
nova.append('                marker_color=VERDE,')
nova.append('                text=df_dias_g["pedidos"],')
nova.append('                textposition="outside",')
nova.append('                textfont=dict(family="Nunito", size=12),')
nova.append('            ))')
nova.append('            fig_dias.update_layout(')
nova.append('                paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",')
nova.append('                margin=dict(t=10, b=10, l=10, r=10),')
nova.append('                xaxis=dict(tickfont=dict(family="Nunito", size=11, color=MARROM)),')
nova.append('                yaxis=dict(showgrid=False, tickfont=dict(family="Nunito", size=11, color=MARROM)),')
nova.append('                font=dict(family="Nunito"), height=350,')
nova.append('            )')
nova.append('            st.plotly_chart(fig_dias, use_container_width=True, key="fig_dias")')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    # Bloco 5 — Mix de pagamento')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Mix de Pagamento</div>\', unsafe_allow_html=True)')
nova.append('        df_pag = df_ifood_pagamentos[df_ifood_pagamentos["periodo"] == periodo_sel_v].groupby("forma_pagamento")["pedidos"].sum().reset_index().sort_values("pedidos", ascending=False)')
nova.append('        fig_pag = go.Figure(go.Pie(')
nova.append('            labels=df_pag["forma_pagamento"],')
nova.append('            values=df_pag["pedidos"],')
nova.append('            hole=0.5,')
nova.append('            textinfo="label+percent",')
nova.append('            textfont=dict(family="Nunito", size=12),')
nova.append('            marker=dict(colors=[VERDE,"#B8923A","#3D7A5C","#7A3D3D","#3D5A7A","#7A5C3D","#5C7A3D","#7A6B3D"]),')
nova.append('        ))')
nova.append('        fig_pag.update_layout(')
nova.append('            paper_bgcolor="rgba(0,0,0,0)",')
nova.append('            margin=dict(t=10, b=10, l=10, r=10),')
nova.append('            legend=dict(font=dict(family="Nunito", size=11, color=MARROM)),')
nova.append('            font=dict(family="Nunito"), height=320,')
nova.append('        )')
nova.append('        st.plotly_chart(fig_pag, use_container_width=True, key="fig_pag")')
nova.append('')

result = lines[:olivia_line] + nova + lines[olivia_line:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print('Feito! Linhas:', len(result))
