lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')
nova = []
nova.append('elif aba_sel == "OlivIA":')
nova.append('    with open("assets/olivia.svg", "r", encoding="utf-8") as svg_f:')
nova.append('        olivia_svg = svg_f.read()')
nova.append('    st.markdown(')
nova.append('        f"""<div style="background:#3D2B1F; border-radius:16px; overflow:hidden; display:flex; align-items:stretch; min-height:240px; margin-bottom:24px;">')
nova.append('        <div style="flex:1; padding:44px 40px 44px 52px; display:flex; flex-direction:column; justify-content:center;">')
nova.append('        <div style="font-size:10px; letter-spacing:4px; color:#8B9A2E; text-transform:uppercase; margin-bottom:14px;">Agente de inteligencia - Olive Garden Brasil</div>')
nova.append('        <div style="font-size:52px; font-weight:800; color:#F5F0E8; letter-spacing:2px; line-height:1; margin-bottom:10px; font-family:Georgia,serif;">Oliv<span style=\'color:#8B9A2E; font-style:italic;\'>IA</span></div>')
nova.append('        <div style="width:52px; height:2px; background:#8B9A2E; margin-bottom:18px;"></div>')
nova.append('        <div style="font-size:13px; color:#D8CFC0; line-height:1.8; max-width:380px;">Analiso reviews, redes sociais, pesquisa interna e noticias do mercado para gerar insights estrategicos em tempo real.</div>')
nova.append('        <div style="margin-top:20px; display:flex; gap:8px; flex-wrap:wrap;">')
nova.append('        <span style="background:rgba(139,154,46,0.2); border:1px solid rgba(139,154,46,0.4); color:#A8BC3A; font-size:10px; letter-spacing:2px; padding:4px 12px; border-radius:20px;">{len(df)} reviews</span>')
nova.append('        <span style="background:rgba(139,154,46,0.2); border:1px solid rgba(139,154,46,0.4); color:#A8BC3A; font-size:10px; letter-spacing:2px; padding:4px 12px; border-radius:20px;">6 filiais</span>')
nova.append('        <span style="background:rgba(139,154,46,0.2); border:1px solid rgba(139,154,46,0.4); color:#A8BC3A; font-size:10px; letter-spacing:2px; padding:4px 12px; border-radius:20px;">powered by Claude</span>')
nova.append('        </div></div>')
nova.append('        <div style="width:280px; background:#4A3525; display:flex; align-items:flex-end; justify-content:center; flex-shrink:0; overflow:hidden;">{olivia_svg}</div>')
nova.append('        </div>""",')
nova.append('        unsafe_allow_html=True')
nova.append('    )')
nova.append('    st.markdown(')
nova.append('        """<div style="background:white; border-radius:12px; border:1px solid #E8DCC8; padding:24px 28px; margin-bottom:24px; display:flex; align-items:center; gap:24px;">')
nova.append('        <div style="width:48px; height:48px; border-radius:50%; background:#4D3321; display:flex; align-items:center; justify-content:center; flex-shrink:0;">')
nova.append('        <svg width=\'20\' height=\'20\' viewBox=\'0 0 24 24\' fill=\'none\'><circle cx=\'12\' cy=\'12\' r=\'10\' stroke=\'#8B9A2E\' stroke-width=\'1.5\'/><path d=\'M8 12h8M12 8v8\' stroke=\'#8B9A2E\' stroke-width=\'1.5\' stroke-linecap=\'round\'/></svg>')
nova.append('        </div>')
nova.append('        <div style="flex:1;">')
nova.append('        <div style="font-size:11px; color:#8B9A2E; letter-spacing:2px; text-transform:uppercase; margin-bottom:4px;">Pronto para analisar</div>')
nova.append('        <div style="font-size:13px; color:#5C3D1E; line-height:1.5;">Clique em <strong style=\'color:#4D3321;\'>Gerar Briefing Executivo</strong> para uma analise completa, ou faca uma pergunta no chat abaixo.</div>')
nova.append('        </div></div>""",')
nova.append('        unsafe_allow_html=True')
nova.append('    )')
result = lines[:859] + nova + lines[871:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print('Feito! Linhas:', len(result))
