lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')

nova = []
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    # Opcao A — Evolucao por dimensao com filtro')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Evolucao por Dimensao e Filial</div>\', unsafe_allow_html=True)')
nova.append('        if len(df_perf) > 1:')
nova.append('            df_perf_ev = df_perf[df_perf["restaurant"] != "nan"].copy()')
nova.append('            df_perf_ev["filial_curta"] = df_perf_ev["restaurant"].str.replace("Olive Garden - ", "")')
nova.append('            df_perf_ev["periodo_curto"] = df_perf_ev["periodo"].str.extract(r"(FW\d+ to FW\d+)")')
nova.append('            metricas_ev = {"overall_experience": "Experiencia Geral", "value": "Valor", "service": "Atendimento", "taste": "Sabor", "speed_of_service": "Velocidade", "clean": "Limpeza", "soup_salad_refill": "Refil Sopa/Salada", "breadstick_refill": "Refil Breadstick"}')
nova.append('            dim_sel = st.selectbox("Selecione a dimensao:", list(metricas_ev.values()), key="dim_sel")')
nova.append('            col_sel = [k for k, v in metricas_ev.items() if v == dim_sel][0]')
nova.append('            fig_ev = go.Figure()')
nova.append('            cores_filiais = ["#8B9A2E", "#B8923A", "#3D7A5C", "#7A3D3D", "#3D5A7A", "#7A5C3D"]')
nova.append('            for idx, filial in enumerate(df_perf_ev["filial_curta"].unique()):')
nova.append('                df_fil = df_perf_ev[df_perf_ev["filial_curta"] == filial].sort_values("periodo_curto")')
nova.append('                fig_ev.add_trace(go.Scatter(')
nova.append('                    x=df_fil["periodo_curto"],')
nova.append('                    y=df_fil[col_sel],')
nova.append('                    mode="lines+markers+text",')
nova.append('                    name=filial,')
nova.append('                    line=dict(color=cores_filiais[idx % len(cores_filiais)], width=2.5),')
nova.append('                    marker=dict(size=10),')
nova.append('                    text=df_fil[col_sel].round(1).astype(str) + "%",')
nova.append('                    textposition="top center",')
nova.append('                    textfont=dict(family="Nunito", size=11),')
nova.append('                ))')
nova.append('            fig_ev.update_layout(')
nova.append('                paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",')
nova.append('                margin=dict(t=20, b=10, l=10, r=10),')
nova.append('                legend=dict(font=dict(family="Nunito", size=11, color=MARROM), orientation="h", yanchor="bottom", y=1.02),')
nova.append('                xaxis=dict(title="", tickfont=dict(family="Nunito", size=11, color=MARROM)),')
nova.append('                yaxis=dict(title="% Topbox", range=[60, 105], showgrid=True, gridcolor="#E8DCC8", tickfont=dict(family="Nunito", size=11, color=MARROM)),')
nova.append('                font=dict(family="Nunito"),')
nova.append('                height=400,')
nova.append('            )')
nova.append('            st.plotly_chart(fig_ev, use_container_width=True, key="fig_ev")')
nova.append('')
nova.append('    st.markdown("<br>", unsafe_allow_html=True)')
nova.append('')
nova.append('    # Opcao C — Small multiples por filial')
nova.append('    with st.container(border=True):')
nova.append('        st.markdown(\'<div class="section-title">Evolucao por Filial — Todas as Dimensoes</div>\', unsafe_allow_html=True)')
nova.append('        if len(df_perf) > 1:')
nova.append('            df_perf_sm = df_perf[df_perf["restaurant"] != "nan"].copy()')
nova.append('            df_perf_sm["filial_curta"] = df_perf_sm["restaurant"].str.replace("Olive Garden - ", "")')
nova.append('            df_perf_sm["periodo_curto"] = df_perf_sm["periodo"].str.extract(r"(FW\d+ to FW\d+)")')
nova.append('            metricas_sm = ["overall_experience", "value", "service", "taste", "speed_of_service", "clean", "soup_salad_refill", "breadstick_refill"]')
nova.append('            labels_sm = ["Exp. Geral", "Valor", "Atend.", "Sabor", "Velocidade", "Limpeza", "Refil Sopa", "Refil Bread"]')
nova.append('            filiais_sm = sorted(df_perf_sm["filial_curta"].unique())')
nova.append('            cols_sm = st.columns(3)')
nova.append('            for idx, filial in enumerate(filiais_sm):')
nova.append('                df_fil = df_perf_sm[df_perf_sm["filial_curta"] == filial].sort_values("periodo_curto")')
nova.append('                fig_sm = go.Figure()')
nova.append('                for m, lbl in zip(metricas_sm, labels_sm):')
nova.append('                    fig_sm.add_trace(go.Scatter(')
nova.append('                        x=df_fil["periodo_curto"],')
nova.append('                        y=df_fil[m],')
nova.append('                        mode="lines+markers",')
nova.append('                        name=lbl,')
nova.append('                        line=dict(width=1.8),')
nova.append('                        marker=dict(size=6),')
nova.append('                    ))')
nova.append('                fig_sm.update_layout(')
nova.append('                    title=dict(text=filial, font=dict(family="Nunito", size=13, color=MARROM), x=0.5),')
nova.append('                    paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",')
nova.append('                    margin=dict(t=40, b=10, l=10, r=10),')
nova.append('                    legend=dict(font=dict(family="Nunito", size=9, color=MARROM), orientation="h", yanchor="bottom", y=-0.5),')
nova.append('                    xaxis=dict(tickfont=dict(family="Nunito", size=9, color=MARROM)),')
nova.append('                    yaxis=dict(range=[60, 105], showgrid=True, gridcolor="#E8DCC8", tickfont=dict(family="Nunito", size=9, color=MARROM)),')
nova.append('                    height=280,')
nova.append('                    font=dict(family="Nunito"),')
nova.append('                )')
nova.append('                with cols_sm[idx % 3]:')
nova.append('                    st.plotly_chart(fig_sm, use_container_width=True, key=f"fig_sm_{idx}")')

result = lines[:809] + nova + lines[809:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print('Feito! Linhas:', len(result))
