lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')
nova = []
nova.append('        with st.container(border=True):')
nova.append('            st.markdown(\'<div class="section-title">Top 10 Posts por Comentários</div>\', unsafe_allow_html=True)')
nova.append('            post_engagement = df_social.groupby("post_url").agg(')
nova.append('                comentarios=("texto", "count"),')
nova.append('                likes_total=("likes", "sum")')
nova.append('            ).reset_index().reset_index()')
nova.append('            post_engagement["label"] = post_engagement["index"].apply(lambda i: f"Post {i+1}")')
nova.append('            post_engagement = post_engagement.sort_values("comentarios", ascending=False).head(10)')
nova.append('            html_posts = ""')
nova.append('            for _, row in post_engagement.iterrows():')
nova.append('                pct = int(row["comentarios"] / post_engagement["comentarios"].max() * 100)')
nova.append('                html_posts += f"""<div style="margin-bottom:10px;">')
nova.append('                    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:4px;">')
nova.append('                        <a href="{row[\'post_url\']}" target="_blank" style="font-size:12px; font-weight:700; color:#5C3D1E; text-decoration:none;">{row[\'label\']} \u2197</a>')
nova.append('                        <span style="font-size:12px; font-weight:700; color:#3D2B1F;">{int(row[\'comentarios\'])} comentarios</span>')
nova.append('                    </div>')
nova.append('                    <div style="background:#e8ddc8; border-radius:4px; height:8px;">')
nova.append('                        <div style="background:#8B9A2E; width:{pct}%; height:8px; border-radius:4px;"></div>')
nova.append('                    </div></div>"""')
nova.append('            st.markdown(html_posts, unsafe_allow_html=True)')
result = lines[:529] + nova + lines[548:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print('Feito! Linhas:', len(result))
