lines = open('dashboard.py', 'r', encoding='utf-8').read().split('\n')
nova = []
nova.append('elif aba_sel == "OlivIA":')
nova.append('    with open("assets/olivia.svg", "r", encoding="utf-8") as svg_f:')
nova.append('        olivia_svg = svg_f.read()')
nova.append('    col_img, col_txt = st.columns([1, 2])')
nova.append('    with col_img:')
nova.append('        st.markdown(olivia_svg, unsafe_allow_html=True)')
nova.append('    with col_txt:')
nova.append('        st.markdown(')
nova.append('            """<div style=\'font-weight:800;font-size:36px;color:#4D3321;margin-top:40px;margin-bottom:8px;\'>Oliv<span style=\'color:#8B9A2E;font-style:italic;\'>IA</span></div><div style=\'font-size:13px;color:#8B9A2E;margin-bottom:16px;\'>AGENTE DE INTELIGENCIA - OLIVE GARDEN BRASIL</div><div style=\'font-size:13px;color:#7a5c3a;line-height:1.9;\'>Ola! Sou a OlivIA.</div>""",')
nova.append('            unsafe_allow_html=True')
nova.append('        )')
result = lines[:859] + nova + lines[865:]
open('dashboard.py', 'w', encoding='utf-8').write('\n'.join(result))
print('Feito! Linhas:', len(result))
